{
  "hash": "1f7e5359b9ff3d4a914ffb1799221581",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Verificación de modelos\"\nsubtitle: \"¿Ajustó bien? ¿Predice bien? ¿Sobran variables?\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n## Resumen\n\nAjustamos un modelo lineal, uno de Poisson y uno logístico y les aplicamos **todas** las pruebas de bondad de ajuste y de capacidad predictiva que se usan en epidemiología: `R²`, `AIC`, ji cuadrada, sobredispersión, Hosmer-Lemeshow, curva ROC, sensibilidad, especificidad, `MAE`, `RMSE` y `WIS`. Usamos un *spline* para descubrir un efecto no lineal y efectos marginales para interpretar. Cada número viene con su lectura, redactada como se redactaría en un artículo.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(haven)\nlibrary(broom)\nlibrary(splines) # para los splines naturales\nlibrary(car) # VIF y pruebas de supuestos\nlibrary(AER) # prueba de sobredispersión\nlibrary(MASS) # binomial negativa\nlibrary(pROC) # curva ROC\nlibrary(ResourceSelection) # Hosmer-Lemeshow\nlibrary(marginaleffects) # efectos marginales\nlibrary(scoringutils) # WIS\nlibrary(forecast) # ARIMA\n\n# Evita que dplyr::select choque con MASS::select\nselect <- dplyr::select\n```\n:::\n\n\n::: callout-important\n## Las dos preguntas que nunca hay que confundir\n\nVerificar un modelo es en realidad **dos** trabajos distintos:\n\n1.  **¿Ajusta bien?** (*bondad de ajuste*). ¿El modelo es compatible con los datos\n    que ya vio? ¿Se cumplen sus supuestos? Aquí viven la `R²`, la ji cuadrada, la\n    prueba de Hosmer-Lemeshow y los residuales.\n\n2.  **¿Predice bien?** (*capacidad predictiva*). ¿Le atina a datos que **no**\n    vio? Aquí viven el `MAE`, el `RMSE`, el área bajo la curva ROC y el `WIS`.\n\nUn modelo puede ajustar perfecto y predecir pésimo (le pasa a cualquier modelo con\ndemasiadas variables), y puede predecir bien con supuestos violados. **Son\npreguntas distintas y se contestan con herramientas distintas.**\n:::\n\n## Los datos\n\nTres bases, cada una para un tipo de modelo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ataques de asma: 120 pacientes (conteo -> Poisson)\nasma <- read_csv(\"datasets/asthma.csv\", show_col_types = FALSE) |>\n  mutate(\n    gender = factor(gender),\n    res_inf = factor(res_inf, levels = c(\"no\", \"yes\"))\n  )\n\n# Evento vascular cerebral: 226 pacientes (sí/no -> logística)\nacv <- read_dta(\"datasets/stroke.dta\") |>\n  mutate(across(where(is.labelled), as_factor)) |>\n  mutate(muerte = as.integer(status == \"dead\"))\n\n# Dengue semanal en Puerto Rico (serie de tiempo)\ndengue <- read_csv(\"datasets/dengue_puerto_rico_semanal.csv\", show_col_types = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Base     |    n|Desenlace                                |Modelo    |\n|:--------|----:|:----------------------------------------|:---------|\n|`asma`   |  120|`attack`: ataques de asma al año (0 a 9) |Poisson   |\n|`acv`    |  226|`status`: vivo o muerto al egreso        |Logística |\n|`dengue` | 1085|`casos`: casos semanales                 |ARIMA     |\n\n\n:::\n:::\n\n\nLas dos primeras vienen de *Data Analysis in Medicine and Health using R*.\n\n## Modelo lineal: presión sistólica al ingreso\n\nEmpecemos con el más sencillo. ¿La presión sistólica al ingreso (`sbp`) depende de\nla edad, el sexo, la diabetes y el tipo de evento?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_lineal <- lm(sbp ~ age + sex + dm + stroke_type, data = acv)\n\ntidy(modelo_lineal, conf.int = TRUE) |>\n  mutate(across(where(is.numeric), ~ round(.x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n  term                   estimate std.error statistic p.value conf.low conf.high\n  <chr>                     <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 (Intercept)             146.       11.5      12.7     0      123.      168.   \n2 age                       0.287     0.167     1.72    0.086   -0.041     0.615\n3 sexfemale                 5.12      4.63      1.11    0.27    -4.01     14.2  \n4 dmyes                    -2.62      4.71     -0.556   0.579  -11.9       6.66 \n5 stroke_typeHaemorrhag…   -3.11      4.89     -0.636   0.526  -12.7       6.53 \n```\n\n\n:::\n:::\n\n\n### `R²` y `R²` ajustada\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(modelo_lineal) |>\n  select(r.squared, adj.r.squared, statistic, p.value, AIC, BIC) |>\n  mutate(across(everything(), ~ round(.x, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  r.squared adj.r.squared statistic p.value   AIC   BIC\n      <dbl>         <dbl>     <dbl>   <dbl> <dbl> <dbl>\n1    0.0251        0.0074      1.42   0.228 2246. 2266.\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Cómo se lee cada número\n\n-   **`r.squared` = 0.025.** El modelo explica el **2.5%** de la variabilidad de la\n    presión sistólica. El otro 97.5% se debe a cosas que no medimos. Se lee así:\n    *\"si te digo la edad, el sexo, la diabetes y el tipo de evento de un paciente,\n    apenas mejoro un 2.5% mi capacidad de adivinar su presión respecto a decir\n    siempre el promedio\"*.\n\n-   **`adj.r.squared` = 0.007.** La `R²` ajustada **castiga por cada variable que\n    metes**. Si al agregar una variable la `R²` sube pero la ajustada baja, esa\n    variable **no está aportando**: sólo está usando grados de libertad. Aquí la\n    caída de 0.025 a 0.007 es una señal de alarma.\n\n-   **`statistic` = 1.42 con `p.value` = 0.23.** Es la prueba `F` **global**:\n    *\"¿este modelo, en conjunto, sirve de algo comparado con no tener modelo?\"*.\n    Con `p = 0.23` la respuesta es **no**. Es la prueba más importante de la tabla\n    y la que más se ignora.\n:::\n\n### Error de predicción: `MAE`, `MSE` y `RMSE`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- residuals(modelo_lineal)\n\nc(\n  MAE = mean(abs(res)),\n  MSE = mean(res^2),\n  RMSE = sqrt(mean(res^2))\n) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    MAE     MSE    RMSE \n  26.81 1149.09   33.90 \n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Los tres errores, en español\n\nLos tres miden lo mismo (qué tan lejos quedó el modelo) pero castigan distinto:\n\n-   **`MAE`** (*error absoluto medio*) = 26.8 mmHg. **El más fácil de explicar**:\n    en promedio, el modelo se equivoca por 26.8 mmHg. Está en las mismas unidades\n    del desenlace, así que se puede poner tal cual en un resultado.\n\n-   **`MSE`** (*error cuadrático medio*) = 1150. Eleva los errores al cuadrado, así\n    que **castiga mucho más los errores grandes**. Su problema: está en mmHg², que\n    no significa nada para nadie.\n\n-   **`RMSE`** = 33.9 mmHg. Es la raíz del `MSE`, así que **regresa a las unidades\n    originales** y sigue castigando los errores grandes.\n\n**La comparación entre `MAE` y `RMSE` te dice algo.** Si `RMSE` es mucho mayor que\n`MAE` (aquí 33.9 contra 26.8), es porque hay **unos pocos errores muy grandes**\njalando el promedio. Si fueran parecidos, los errores estarían repartidos parejo.\n:::\n\n### Supuestos: normalidad, homocedasticidad y colinealidad\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ¿Los residuales son normales?\nshapiro.test(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  res\nW = 0.99046, p-value = 0.1436\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ¿La varianza es constante? (Breusch-Pagan)\nncvTest(modelo_lineal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNon-constant Variance Score Test \nVariance formula: ~ fitted.values \nChisquare = 0.0195577, Df = 1, p = 0.88878\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ¿Hay variables que se explican entre sí?\nvif(modelo_lineal) |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        age         sex          dm stroke_type \n      1.037       1.010       1.013       1.033 \n```\n\n\n:::\n:::\n\n\n::: callout-important\n## La lección más importante de este capítulo\n\nMira lo que acaba de pasar. **Todos los supuestos se cumplen**:\n\n| Prueba | Resultado | Lectura |\n|:-------|:----------|:--------|\n| Shapiro-Wilk | `p` = 0.14 | No se rechaza la normalidad de los residuales |\n| Breusch-Pagan | `p` = 0.89 | La varianza es constante |\n| `VIF` | todos ≈ 1 | Sin colinealidad |\n\nY sin embargo el modelo **no sirve**: `R²` de 0.025 y prueba `F` global con\n`p` = 0.23.\n\n> **Que un modelo cumpla sus supuestos no quiere decir que sea útil.** Los\n> supuestos dicen si el modelo está *bien construido*; la `R²` y la `F` dicen si\n> *tiene algo que decir*. Un modelo puede estar impecablemente construido sobre\n> variables que no explican nada.\n\nCómo se reportaría esto en un artículo:\n\n> *La presión sistólica al ingreso no se asoció de manera significativa con la\n> edad, el sexo, el antecedente de diabetes ni el tipo de evento vascular\n> (F(4,221) = 1.42; p = 0.23; R² ajustada = 0.007). Los supuestos de normalidad\n> de residuales (Shapiro-Wilk p = 0.14) y homocedasticidad (Breusch-Pagan\n> p = 0.89) se cumplieron.*\n\nFíjate que **se reporta el resultado nulo con todo y sus pruebas de supuestos**.\nUn resultado nulo bien hecho es un resultado.\n:::\n\n## Modelo de Poisson: ataques de asma\n\nAhora un conteo: número de ataques de asma al año, según el puntaje de malestar\npsicológico `GHQ-12`, si hay infección respiratoria recurrente y el sexo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_poisson <- glm(attack ~ ghq12 + res_inf + gender,\n  data = asma, family = poisson()\n)\n\nexp(cbind(IRR = coef(modelo_poisson), confint.default(modelo_poisson))) |>\n  round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              IRR 2.5 % 97.5 %\n(Intercept) 0.730 0.509  1.045\nghq12       1.051 1.035  1.067\nres_infyes  1.532 1.135  2.067\ngendermale  0.959 0.754  1.219\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Cómo se lee una razón de tasas de incidencia (`IRR`)\n\n-   **`ghq12` = 1.051.** Por cada punto más en la escala GHQ-12, el número esperado\n    de ataques se multiplica por 1.051, es decir **aumenta 5.1%**. Como el\n    intervalo (1.035–1.067) **no incluye al 1**, es estadísticamente significativo.\n\n-   **`res_infyes` = 1.532.** Quienes tienen infección respiratoria recurrente\n    tienen **53% más ataques** que quienes no, ajustando por GHQ-12 y sexo.\n\n-   **`gendermale` = 0.959**, intervalo 0.754–1.219: **incluye al 1**, así que no\n    hay evidencia de diferencia por sexo.\n\nEn Poisson **siempre** se exponencia. Los coeficientes crudos están en escala\nlogarítmica y no se interpretan directamente.\n:::\n\n### Bondad de ajuste: ¿se cumple el supuesto de Poisson?\n\nLa Poisson supone que **la varianza es igual a la media**. Hay que revisarlo\nsiempre.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Los datos crudos: ¿varianza = media?\nc(media = mean(asma$attack), varianza = var(asma$attack)) |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   media varianza \n   2.458    4.049 \n```\n\n\n:::\n:::\n\n\nA primera vista hay problema: la varianza (4.05) es **1.65 veces** la media (2.46).\nPero eso es la dispersión **cruda**. Lo que le importa al modelo es la dispersión\n**después de ajustar por las covariables**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tres formas de medir lo mismo\nc(\n  deviance_gl = modelo_poisson$deviance / modelo_poisson$df.residual,\n  pearson_gl = sum(residuals(modelo_poisson, \"pearson\")^2) /\n    modelo_poisson$df.residual\n) |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndeviance_gl  pearson_gl \n      1.178       1.061 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prueba formal de sobredispersión\ndispersiontest(modelo_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOverdispersion test\n\ndata:  modelo_poisson\nz = 0.43048, p-value = 0.3334\nalternative hypothesis: true dispersion is greater than 1\nsample estimates:\ndispersion \n  1.046941 \n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Sobredispersión cruda ≠ sobredispersión condicional\n\nLos datos crudos parecían sobredispersos (1.65) y el modelo **no lo está** (1.05,\n`p` = 0.33).\n\n¿Por qué? Porque **las covariables explicaron ese exceso de varianza**. La gente\ncon GHQ-12 alto tiene muchos ataques y la de GHQ-12 bajo tiene pocos; visto todo\njunto eso se ve como \"mucha variabilidad\", pero una vez que el modelo sabe el\nGHQ-12 de cada quien, lo que sobra es justo lo que la Poisson espera.\n\n> Nunca decidas usar binomial negativa mirando la media y la varianza crudas.\n> **Se decide con los residuales del modelo ajustado.**\n:::\n\n### La prueba ji cuadrada de bondad de ajuste\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ¿La devianza residual es compatible con una ji cuadrada?\npchisq(modelo_poisson$deviance, modelo_poisson$df.residual,\n  lower.tail = FALSE\n) |> round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0922\n```\n\n\n:::\n:::\n\n\n::: callout-tip\nÉsta es la **prueba de bondad de ajuste por devianza**. La hipótesis nula es que\n*el modelo ajusta bien*, así que aquí un `p` **grande** es buena noticia (al revés\nde lo acostumbrado).\n\nCon `p` = 0.09 no se rechaza el ajuste, aunque está en la frontera. Se reporta así:\n*\"no se encontró evidencia de falta de ajuste (prueba de devianza, p = 0.09)\"*.\n:::\n\n### ¿Y si usáramos binomial negativa?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_nb <- glm.nb(attack ~ ghq12 + res_inf + gender, data = asma)\n\nc(\n  AIC_Poisson = AIC(modelo_poisson),\n  AIC_BinomialNegativa = AIC(modelo_nb)\n) |> round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         AIC_Poisson AIC_BinomialNegativa \n               417.7                419.7 \n```\n\n\n:::\n:::\n\n\n::: callout-note\nEl `AIC` de la Poisson (417.7) es **menor** que el de la binomial negativa (419.7),\nasí que la Poisson gana. Tiene sentido: la binomial negativa agrega un parámetro\nextra para la sobredispersión, y aquí no hay sobredispersión que modelar, así que\nsólo paga el costo del parámetro sin ganancia.\n\n**Regla del `AIC`: entre más chico, mejor**, y una diferencia menor a 2 se\nconsidera empate. Aquí la diferencia es exactamente 2, lo que refuerza quedarse\ncon el modelo **más simple**.\n:::\n\n### Un *spline*: ¿el efecto del GHQ-12 es realmente lineal?\n\nEl modelo supone que cada punto de GHQ-12 pesa igual, tanto del 2 al 3 como del 30\nal 31. **Eso es una suposición fuerte** y se puede probar. Un *spline natural*\npermite que la curva tome la forma que quiera:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_spline <- glm(attack ~ ns(ghq12, df = 4) + res_inf + gender,\n  data = asma, family = poisson()\n)\n\nanova(modelo_poisson, modelo_spline, test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: attack ~ ghq12 + res_inf + gender\nModel 2: attack ~ ns(ghq12, df = 4) + res_inf + gender\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1       116     136.68                          \n2       113     115.85  3   20.828 0.0001143 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  AIC_lineal = AIC(modelo_poisson),\n  AIC_spline = AIC(modelo_spline)\n) |> round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAIC_lineal AIC_spline \n     417.7      402.9 \n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Sí hay no linealidad, y es fuerte\n\nLa prueba de razón de verosimilitudes da `p` = 0.0001 y el `AIC` baja de **417.7 a\n402.9** (casi 15 puntos: una diferencia enorme).\n\nConclusión: **el efecto del GHQ-12 no es una línea recta**. El modelo lineal estaba\npromediando formas distintas en un solo número.\n:::\n\nVeamos la forma que tiene:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmalla <- expand_grid(\n  ghq12 = seq(0, 33, by = 0.5),\n  res_inf = factor(\"no\", levels = c(\"no\", \"yes\")),\n  gender = factor(\"female\", levels = c(\"female\", \"male\"))\n)\n\npred_spl <- predictions(modelo_spline, newdata = malla)\n\nggplot(pred_spl, aes(x = ghq12, y = estimate)) +\n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),\n    fill = \"#003f5c\", alpha = 0.2\n  ) +\n  geom_line(color = \"#003f5c\", linewidth = 1) +\n  geom_rug(data = asma, aes(x = ghq12, y = NULL), alpha = 0.3) +\n  labs(\n    x = \"Puntaje GHQ-12 (malestar psicológico)\",\n    y = \"Ataques de asma esperados al año\",\n    title = \"El efecto del malestar psicológico no es lineal\",\n    caption = \"Mujeres sin infección respiratoria recurrente. Las marcas de abajo son los datos observados.\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Efecto del GHQ-12 sobre el número esperado de ataques, con spline natural.](verificacion-modelos_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nY la **pendiente local** en distintos puntos de la escala:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npuntos <- data.frame(\n  ghq12 = c(3, 9, 15, 21, 27),\n  res_inf = factor(\"no\", levels = c(\"no\", \"yes\")),\n  gender = factor(\"female\", levels = c(\"female\", \"male\"))\n)\n\nslopes(modelo_spline, newdata = puntos, variables = \"ghq12\") |>\n  as.data.frame() |>\n  select(ghq12, estimate, conf.low, conf.high, p.value) |>\n  mutate(across(-1, ~ round(.x, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ghq12 estimate conf.low conf.high p.value\n1     3  -0.0854  -0.1828    0.0119  0.0855\n2     9   0.0724   0.0361    0.1086  0.0001\n3    15   0.3219   0.1632    0.4805  0.0001\n4    21  -0.0073  -0.2092    0.1945  0.9434\n5    27   0.0024  -0.1430    0.1479  0.9741\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Cómo se interpreta esto en un artículo\n\nLa curva y las pendientes locales cuentan una historia **de umbral**:\n\n-   **Por debajo de GHQ-12 ≈ 6** la curva es plana: el malestar psicológico bajo no\n    se asocia a más ataques.\n-   **Entre 6 y 18** la curva sube con fuerza y las pendientes son significativas:\n    ahí es donde el malestar sí importa.\n-   **Arriba de 18** vuelve a aplanarse: ya no empeora más.\n\nRedactado como en un artículo:\n\n> *Se modeló el puntaje GHQ-12 mediante un spline natural con 4 grados de libertad.\n> El término no lineal resultó significativo frente al modelo lineal (prueba de\n> razón de verosimilitudes, p = 0.0001; ΔAIC = 14.8), lo que indica una relación\n> no lineal. La tasa de ataques permaneció estable en puntajes bajos, aumentó de\n> forma marcada entre 6 y 18 puntos y se estabilizó posteriormente, lo que sugiere\n> un efecto de umbral.*\n\n**El modelo lineal habría reportado \"5.1% más ataques por punto\" y eso es\nengañoso**: no aplica ni abajo ni arriba de la escala, sólo en medio.\n:::\n\n::: callout-warning\n## El spline también cambió otra conclusión\n\nCompara la `IRR` de infección recurrente en los dos modelos:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                  res_infyes 2.5 % 97.5 %\nModelo lineal          1.532 1.135  2.067\nModelo con spline      1.257 0.922  1.713\n```\n\n\n:::\n:::\n\n\nPasó de 1.53 (significativa) a 1.26 (**no** significativa). Lo que ocurría es que\nel modelo lineal, al no capturar bien el efecto del GHQ-12, **le estaba\natribuyendo parte de ese efecto a la infección recurrente**.\n\n> Especificar mal una variable de ajuste **sesga los coeficientes de las demás**.\n> Es una forma de confusión residual, y es de las más comunes y menos revisadas.\n:::\n\n### Efectos marginales\n\nLos coeficientes de un modelo de Poisson están en escala multiplicativa. Los\n**efectos marginales** los traducen a la escala del desenlace: *\"¿cuántos ataques\nmás, en números?\"*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_slopes(modelo_spline)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    Term      Contrast Estimate Std. Error     z Pr(>|z|)   S   2.5 % 97.5 %\n gender  male - female   0.1286     0.3117 0.413    0.680 0.6 -0.4823 0.7396\n ghq12   dY/dX           0.0152     0.0168 0.904    0.366 1.5 -0.0178 0.0482\n res_inf yes - no        0.5321     0.3492 1.524    0.128 3.0 -0.1524 1.2166\n\nType: response\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Ojo con el efecto marginal promedio en modelos no lineales\n\nEl efecto marginal promedio del GHQ-12 sale **no significativo** (`p` ≈ 0.37)\naunque el spline **sí** lo es (`p` = 0.0001). No es contradicción:\n\nEl efecto marginal *promedio* saca un promedio de la pendiente **a lo largo de toda\nla curva**. Como la curva sube fuerte en medio y es plana en los extremos, al\npromediarla los efectos **se cancelan** y queda un número chico y con mucha\nincertidumbre.\n\n> Cuando el efecto no es lineal, **el efecto marginal promedio esconde justo lo\n> interesante**. Reporta la curva y las pendientes locales, no un solo número.\n:::\n\n## Modelo logístico: mortalidad hospitalaria\n\nAhora un desenlace binario: si el paciente falleció durante la hospitalización.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_logistico <- glm(muerte ~ gcs + age + sex + dm + stroke_type,\n  data = acv, family = binomial()\n)\n\nexp(cbind(OR = coef(modelo_logistico), confint.default(modelo_logistico))) |>\n  round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           OR 2.5 % 97.5 %\n(Intercept)             0.979 0.077 12.394\ngcs                     0.720 0.645  0.803\nage                     1.025 0.995  1.056\nsexfemale               1.537 0.654  3.613\ndmyes                   1.599 0.682  3.754\nstroke_typeHaemorrhagic 3.522 1.506  8.238\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Interpretación\n\n-   **`gcs` = 0.720.** Por cada punto más en la escala de coma de Glasgow, los\n    momios de morir se multiplican por 0.72, o sea **bajan 28%**. Es protector y su\n    intervalo (0.645–0.803) no toca el 1.\n\n-   **`stroke_typeHaemorrhagic` = 3.522.** Los eventos hemorrágicos tienen **3.5\n    veces los momios** de muerte que los isquémicos, ajustando por lo demás.\n    Intervalo 1.51–8.24: significativo pero **muy ancho**, porque son sólo 226\n    pacientes.\n\n-   **`age`, `sex`, `dm`**: todos con intervalos que incluyen el 1. Sin evidencia\n    de asociación.\n:::\n\n### Bondad de ajuste global\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pseudo R2 de McFadden y prueba de razón de verosimilitudes global\nc(\n  pseudo_R2_McFadden = 1 - modelo_logistico$deviance / modelo_logistico$null.deviance,\n  AIC = AIC(modelo_logistico)\n) |> round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npseudo_R2_McFadden                AIC \n            0.3647           171.3576 \n```\n\n\n:::\n\n```{.r .cell-code}\nanova(modelo_logistico, test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel: binomial, link: logit\n\nResponse: muerte\n\nTerms added sequentially (first to last)\n\n            Df Deviance Resid. Df Resid. Dev  Pr(>Chi)    \nNULL                          225     250.83              \ngcs          1   79.907       224     170.92 < 2.2e-16 ***\nage          1    1.391       223     169.53  0.238311    \nsex          1    0.783       222     168.75  0.376252    \ndm           1    1.020       221     167.73  0.312478    \nstroke_type  1    8.368       220     159.36  0.003818 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: callout-note\nLa **pseudo `R²` de McFadden** (0.365) **no se lee como la `R²` de siempre**. En\nregresión logística no existe una \"proporción de varianza explicada\". Valores de\n**0.2 a 0.4 ya se consideran un ajuste excelente**. Un 0.365 aquí es muy bueno.\n\nLa tabla de `anova` con `test = \"LRT\"` agrega las variables una por una y prueba si\ncada una aporta. Es la forma correcta de evaluar **variables categóricas con varios\nniveles**, donde mirar los `p` uno por uno no sirve.\n:::\n\n### Calibración: la prueba de Hosmer-Lemeshow\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhoslem.test(modelo_logistico$y, fitted(modelo_logistico), g = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tHosmer and Lemeshow goodness of fit (GOF) test\n\ndata:  modelo_logistico$y, fitted(modelo_logistico)\nX-squared = 5.5516, df = 8, p-value = 0.6973\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Qué mide y cómo se lee\n\nHosmer-Lemeshow parte a los pacientes en 10 grupos según su riesgo predicho y\ncompara, en cada grupo, **cuántas muertes predijo el modelo contra cuántas hubo**.\n\nLa hipótesis nula es que **el modelo está bien calibrado**, así que —igual que con\nla devianza— **un `p` grande es buena noticia**.\n\nAquí `χ²` = 5.55 con 8 grados de libertad y `p` = 0.70: **no hay evidencia de mala\ncalibración**. Cuando el modelo dice \"30% de riesgo\", muere alrededor del 30%.\n\n> Calibración y discriminación son **cosas distintas**. Un modelo puede ordenar\n> perfectamente a los pacientes (buena discriminación) y aun así equivocarse en la\n> magnitud del riesgo (mala calibración). Hay que reportar las dos.\n:::\n\n### Discriminación: la curva ROC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroc_obj <- roc(modelo_logistico$y, fitted(modelo_logistico), quiet = TRUE)\n\nggroc(roc_obj, color = \"#003f5c\", linewidth = 1) +\n  geom_abline(intercept = 1, slope = 1, linetype = \"dashed\", color = \"gray50\") +\n  annotate(\"text\",\n    x = 0.3, y = 0.2,\n    label = paste0(\"AUC = \", round(auc(roc_obj), 3)), size = 5\n  ) +\n  labs(\n    x = \"Especificidad\", y = \"Sensibilidad\",\n    title = \"¿Qué tan bien distingue el modelo quién muere?\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Curva ROC del modelo de mortalidad.](verificacion-modelos_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci.auc(roc_obj) |> round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8435 0.8915 0.9395\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## El `AUC` y su intervalo\n\n`AUC` = 0.892 (IC 95%: 0.844–0.940). Se interpreta así: **si tomas al azar un\npaciente que murió y uno que sobrevivió, el modelo le asigna mayor riesgo al que\nmurió el 89% de las veces**.\n\n| `AUC` | Lectura |\n|:------|:--------|\n| 0.5 | El modelo no discrimina (equivale a una moneda) |\n| 0.7–0.8 | Aceptable |\n| 0.8–0.9 | Bueno |\n| \\> 0.9 | Excelente |\n\n**Siempre reporta el intervalo de confianza.** Un `AUC` de 0.89 con IC de\n0.84–0.94 es sólido; el mismo 0.89 con IC de 0.60–0.98 no dice nada.\n:::\n\n### Sensibilidad, especificidad y compañía\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob <- fitted(modelo_logistico)\npred_05 <- as.integer(prob >= 0.5)\n\ntabla <- table(Predicho = factor(pred_05, 0:1), Real = factor(modelo_logistico$y, 0:1))\ntabla\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Real\nPredicho   0   1\n       0 160  26\n       1  11  29\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas <- function(tab) {\n  VP <- tab[\"1\", \"1\"]\n  VN <- tab[\"0\", \"0\"]\n  FP <- tab[\"1\", \"0\"]\n  FN <- tab[\"0\", \"1\"]\n  c(\n    Sensibilidad = VP / (VP + FN), # recall\n    Especificidad = VN / (VN + FP),\n    Precision_VPP = VP / (VP + FP),\n    VPN = VN / (VN + FN),\n    Exactitud = (VP + VN) / sum(tab),\n    F1 = 2 * VP / (2 * VP + FP + FN)\n  )\n}\n\nmetricas(tabla) |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Sensibilidad Especificidad Precision_VPP           VPN     Exactitud \n        0.527         0.936         0.725         0.860         0.836 \n           F1 \n        0.611 \n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Aquí está la trampa más común en modelos de predicción clínica\n\nLa **exactitud es 0.836**: el modelo acierta en el 84% de los pacientes. Suena\nexcelente.\n\nPero mira la **sensibilidad: 0.527**. De los 55 pacientes que murieron, el modelo\nsólo identificó a 29. **Se le escapó casi la mitad de las muertes.**\n\n¿Cómo puede tener 84% de exactitud entonces? Porque el **76% de los pacientes\nsobrevivió**, y el modelo es buenísimo detectando a los que sobreviven\n(especificidad 0.936). La exactitud está inflada por la clase mayoritaria.\n\n> **En desenlaces poco frecuentes, la exactitud es una métrica engañosa.** Si el\n> 95% de tus pacientes sobrevive, un modelo que diga \"todos viven\" tiene 95% de\n> exactitud y es completamente inútil. Reporta siempre sensibilidad y\n> especificidad por separado.\n\nLos nombres que vas a encontrar en la literatura:\n\n| En epidemiología | En ciencia de datos | Qué contesta |\n|:-----------------|:--------------------|:-------------|\n| Sensibilidad | *Recall* | De los que murieron, ¿a cuántos detecté? |\n| Especificidad | — | De los que vivieron, ¿a cuántos descarté bien? |\n| Valor predictivo positivo | *Precision* | De los que marqué, ¿cuántos sí murieron? |\n| Valor predictivo negativo | — | De los que descarté, ¿cuántos sí vivieron? |\n:::\n\n### El punto de corte no es 0.5\n\nEl `0.5` que usamos es una convención, **no un resultado estadístico**. El índice\nde Youden busca el corte que maximiza sensibilidad + especificidad:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorte <- coords(roc_obj, \"best\", ret = c(\"threshold\", \"sensitivity\", \"specificity\"))\ncorte |> mutate(across(everything(), ~ round(.x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  threshold sensitivity specificity\n1     0.195       0.855       0.813\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_youden <- table(\n  Predicho = factor(as.integer(prob >= corte$threshold), 0:1),\n  Real = factor(modelo_logistico$y, 0:1)\n)\nmetricas(tabla_youden) |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Sensibilidad Especificidad Precision_VPP           VPN     Exactitud \n        0.855         0.813         0.595         0.946         0.823 \n           F1 \n        0.701 \n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Compara las dos tablas\n\n| Corte | Sensibilidad | Especificidad | Exactitud |\n|:------|:-------------|:--------------|:----------|\n| 0.50 | 0.527 | 0.936 | 0.836 |\n| 0.195 (Youden) | 0.855 | 0.766 | 0.788 |\n\nBajando el corte, la sensibilidad **sube de 53% a 86%** a costa de bajar la\nespecificidad y la exactitud global.\n\n**¿Cuál está bien? Depende de qué cuesta cada error**, y ésa es una decisión\nclínica y de política, no estadística:\n\n-   Si el modelo sirve para **decidir a quién vigilar más de cerca**, no detectar\n    una muerte es gravísimo y una falsa alarma es barata → corte bajo.\n-   Si sirviera para **decidir a quién NO tratar**, sería al revés.\n\n> Es la misma idea del [capítulo de modelos](modelos.qmd): el punto de corte lo\n> pones tú, y hay que justificarlo en la sección de métodos.\n:::\n\n### El puntaje de Brier\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(Brier = mean((prob - modelo_logistico$y)^2)) |> round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Brier \n0.1104 \n```\n\n\n:::\n:::\n\n\n::: callout-note\nEl **puntaje de Brier** (0.110) es el error cuadrático medio de las probabilidades\npredichas. Va de 0 (perfecto) a 0.25 (inútil, cuando predices 0.5 siempre).\n\nSu virtud es que **combina calibración y discriminación en un solo número**. Su\ndefecto es que, justo por eso, no te dice cuál de las dos falló.\n:::\n\n### Efectos marginales del modelo logístico\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_slopes(modelo_logistico)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n        Term                        Contrast Estimate Std. Error      z\n age         dY/dX                            0.00262    0.00162  1.621\n dm          yes - no                         0.04963    0.04516  1.099\n gcs         dY/dX                           -0.03519    0.00420 -8.371\n sex         female - male                    0.04596    0.04639  0.991\n stroke_type Haemorrhagic - Ischaemic Stroke  0.15981    0.06157  2.595\n Pr(>|z|)    S     2.5 %   97.5 %\n  0.10509  3.3 -0.000548  0.00579\n  0.27175  1.9 -0.038877  0.13814\n  < 0.001 54.0 -0.043425 -0.02695\n  0.32177  1.6 -0.044957  0.13688\n  0.00945  6.7  0.039127  0.28049\n\nType: response\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## De momios a puntos porcentuales\n\nAquí está la razón por la que valen tanto la pena los efectos marginales. El `OR`\ndel Glasgow era 0.72, que no le dice nada útil a un clínico. El efecto marginal\npromedio dice:\n\n> *Cada punto adicional en la escala de Glasgow se asocia con una reducción\n> absoluta de 3.5 puntos porcentuales en la probabilidad de morir\n> (IC 95%: 2.7 a 4.3).*\n\nEso **sí** se entiende y **sí** se puede usar para decidir. Es la traducción de la\nescala del modelo a la escala del mundo.\n:::\n\n## Series de tiempo: dengue\n\nPara pronósticos las métricas son otras, porque hay que evaluar contra datos\nfuturos que el modelo no vio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nH <- 52\nentrena <- head(dengue, nrow(dengue) - H)\nprueba <- tail(dengue, H)\n\nserie <- ts(entrena$casos, frequency = 52)\nfourier_dentro <- fourier(serie, K = 3)\nfourier_fuera <- fourier(serie, K = 3, h = H)\n\nmodelo_arima <- auto.arima(serie, seasonal = FALSE, xreg = fourier_dentro)\npron_arima <- forecast(modelo_arima, xreg = fourier_fuera, level = c(50, 80, 90, 95))\n\n# Modelo ingenuo: \"va a pasar lo mismo que hace un año\"\ningenuo <- tail(entrena$casos, H)\n```\n:::\n\n\n### `MAE`, `MSE`, `RMSE` y `MAPE`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_punto <- function(pred, obs) {\n  c(\n    MAE = mean(abs(pred - obs)),\n    MSE = mean((pred - obs)^2),\n    RMSE = sqrt(mean((pred - obs)^2)),\n    MAPE = mean(abs((pred - obs) / obs)) * 100\n  )\n}\n\nrbind(\n  ARIMA = metricas_punto(as.numeric(pron_arima$mean), prueba$casos),\n  Ingenuo = metricas_punto(ingenuo, prueba$casos)\n) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           MAE      MSE   RMSE  MAPE\nARIMA    98.46 17480.86 132.22 64.00\nIngenuo 101.25 18811.75 137.16 63.04\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Las métricas pueden contradecirse, y hay que saber cuál creer\n\nFíjate bien:\n\n-   Por `MAE` (98.5 contra 101.3), `MSE` y `RMSE`, **gana el ARIMA**.\n-   Por `MAPE` (64.0 contra 63.0), **gana el modelo ingenuo**.\n\n¿Quién tiene razón? El problema es del `MAPE`: divide el error entre el valor\nobservado, así que **las semanas con pocos casos dominan el promedio**. Errarle por\n5 casos cuando hubo 10 cuenta como 50% de error; errarle por 50 cuando hubo 500\ncuenta como 10%. En vigilancia epidemiológica, donde hay semanas con muy pocos\ncasos, el `MAPE` es casi siempre mala idea.\n\n> Escoge la métrica **antes** de ver los resultados y justifícala. Si eliges la\n> métrica después, siempre vas a encontrar una que favorezca a tu modelo.\n:::\n\n### El `WIS`: la métrica que sí toma en cuenta la incertidumbre\n\nTodas las anteriores comparan **un solo número** predicho contra el observado, e\nignoran por completo si el modelo dijo estar seguro o no. El `WIS` (*Weighted\nInterval Score*) evalúa **el intervalo completo**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.table::setDTthreads(1)\n\nniveles <- c(0.025, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.975)\n\nq_arima <- cbind(\n  pron_arima$lower[, 4], pron_arima$lower[, 3],\n  pron_arima$lower[, 2], pron_arima$lower[, 1],\n  pron_arima$mean,\n  pron_arima$upper[, 1], pron_arima$upper[, 2],\n  pron_arima$upper[, 3], pron_arima$upper[, 4]\n)\nsd_ingenuo <- sd(diff(entrena$casos, lag = 52), na.rm = TRUE)\nq_ingenuo <- sapply(niveles, function(q) ingenuo + qnorm(q) * sd_ingenuo)\n\narmar <- function(q, nombre) {\n  tibble(\n    modelo = nombre,\n    semana = rep(prueba$semana, times = length(niveles)),\n    observado = rep(prueba$casos, times = length(niveles)),\n    nivel = rep(niveles, each = H),\n    prediccion = as.vector(q)\n  )\n}\n\nevaluacion <- bind_rows(armar(q_arima, \"ARIMA\"), armar(q_ingenuo, \"Ingenuo\")) |>\n  as_forecast_quantile(\n    forecast_unit = c(\"modelo\", \"semana\"),\n    observed = \"observado\", predicted = \"prediccion\",\n    quantile_level = \"nivel\"\n  ) |>\n  score() |>\n  summarise_scores(by = \"modelo\")\n\nevaluacion |>\n  select(\n    modelo, wis, dispersion, underprediction, overprediction,\n    interval_coverage_50, interval_coverage_90\n  ) |>\n  mutate(across(-1, ~ round(.x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    modelo    wis dispersion underprediction overprediction\n    <char>  <num>      <num>           <num>          <num>\n1:   ARIMA 54.068     11.902          42.154          0.012\n2: Ingenuo 64.826     11.423          53.396          0.006\n   interval_coverage_50 interval_coverage_90\n                  <num>                <num>\n1:                0.269                0.673\n2:                0.346                0.673\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Cómo se lee el `WIS` y por qué es la mejor métrica para vigilancia\n\nEl `WIS` cobra tres cosas a la vez: **qué tan ancho** es el intervalo (para que no\nhagas trampa diciendo \"entre 0 y un millón\"), **qué tanto se quedó corto** y **qué\ntanto se pasó**. Entre más chico, mejor.\n\n-   `ARIMA` = 54.1 contra `Ingenuo` = 64.8: el ARIMA gana, y aquí **sin ambigüedad**\n    (a diferencia del `MAPE`).\n-   La descomposición dice **por qué**: casi todo el puntaje de ambos es\n    **subestimación** (42.2 y 53.4), y casi nada es sobreestimación. Los dos se\n    quedaron cortos, el ingenuo más.\n-   **La cobertura es lo más revelador**: los intervalos al 90% sólo contuvieron el\n    valor real el **67%** de las veces. Deberían ser 90%.\n\nRedactado como en un artículo:\n\n> *El modelo ARIMA con términos de Fourier superó al modelo estacional ingenuo\n> (WIS 54.1 frente a 64.8). La descomposición del WIS indicó que el error se debió\n> predominantemente a subestimación. La cobertura empírica de los intervalos de\n> predicción al 90% fue de 67%, por debajo del nivel nominal, lo que sugiere que\n> los intervalos son demasiado estrechos y que la incertidumbre está subestimada.*\n:::\n\n## Resumen: qué métrica para qué\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Qué quiero saber                 |Herramienta                             |Modelo           |\n|:--------------------------------|:---------------------------------------|:----------------|\n|¿El modelo explica algo?         |R², prueba F global                     |Lineal           |\n|¿Sobran variables?               |R² ajustada, AIC, BIC                   |Todos            |\n|¿Se cumplen los supuestos?       |Shapiro-Wilk, Breusch-Pagan, residuales |Lineal           |\n|¿Hay variables redundantes?      |VIF                                     |Todos            |\n|¿Qué tan lejos quedé?            |MAE, RMSE (MSE si comparas)             |Lineal / series  |\n|¿El conteo está sobredisperso?   |Devianza/gl, dispersiontest             |Poisson          |\n|¿El riesgo predicho es correcto? |Hosmer-Lemeshow, Brier                  |Logística        |\n|¿Ordena bien a los pacientes?    |AUC (curva ROC)                         |Logística        |\n|¿A cuántos enfermos detecto?     |Sensibilidad (no exactitud)             |Logística        |\n|¿Mi pronóstico es honesto?       |WIS y cobertura                         |Series de tiempo |\n\n\n:::\n:::\n\n\n::: callout-warning\n## Los cinco errores más comunes al reportar modelos\n\n1.  **Reportar `R²` sin la prueba `F`.** Una `R²` de 0.30 con `p` = 0.4 no es nada.\n2.  **Reportar exactitud en desenlaces poco frecuentes.** Siempre da bien y siempre\n    engaña. Usa sensibilidad y especificidad.\n3.  **Decidir binomial negativa por la varianza cruda.** Se decide con los\n    residuales del modelo.\n4.  **Interpretar el `OR` como riesgo.** Si el desenlace es común, exagera (ver el\n    [capítulo de encuestas](analisis-encuestas.qmd)).\n5.  **Suponer linealidad sin probarla.** Un spline cuesta dos líneas de código y\n    aquí cambió las conclusiones.\n:::\n\n## Ejercicios\n\n### Interpretación\n\n1.  El modelo lineal tuvo `R²` = 0.025 y todos sus supuestos se cumplieron. Escribe\n    dos o tres renglones explicándole a alguien que no sabe estadística por qué\n    \"cumplir los supuestos\" y \"servir\" no son lo mismo.\n\n2.  Un colega te dice: *\"mi modelo tiene 92% de exactitud para predecir muerte\n    materna\"*. La mortalidad materna ocurre en menos del 0.1% de los embarazos.\n    ¿Qué le preguntas antes de creerle?\n\n3.  Con la tabla de cortes (0.5 contra 0.195), ¿cuál usarías si el modelo fuera a\n    servir para decidir a qué pacientes se les asigna cama de terapia intensiva?\n    Justifica en términos de qué cuesta cada tipo de error.\n\n### Cálculo\n\n4.  Ajusta el modelo logístico **sin** `gcs` y compara el `AUC` con el que tiene.\n    ¿Cuánto de la capacidad predictiva venía de esa sola variable?\n\n5.  Corre `anova(modelo_logistico, test = \"LRT\")` y decide, con ese criterio, qué\n    variables quitarías. Ajusta el modelo reducido y compara los `AIC`.\n\n6.  Prueba splines con 3, 4 y 5 grados de libertad para el `ghq12`. ¿Cuál elige el\n    `AIC`? ¿Cambia la forma de la curva?\n\n7.  Calcula el `MAE` y el `RMSE` del modelo de Poisson (compara `attack` observado\n    contra `fitted(modelo_poisson)`). ¿Por qué el `RMSE` es mayor?\n\n### A mano\n\n8.  Con la matriz de confusión del corte 0.5, calcula **con calculadora** la\n    sensibilidad, la especificidad y el valor predictivo positivo. Verifica con la\n    función `metricas`.\n\n9.  Si un modelo tiene sensibilidad 0.90 y especificidad 0.90, y lo aplicas a una\n    población donde el desenlace ocurre en el 1%, ¿cuál es el valor predictivo\n    positivo? (Pista: usa el teorema de Bayes o arma una tabla con 10,000\n    personas.) ¿Te sorprende el resultado?\n\n### Con apoyo de una IA\n\n10. Pásale a una IA la tabla de métricas de clasificación del corte 0.5 y pregúntale\n    si el modelo es bueno. Si contesta que sí basándose en la exactitud, corrígela\n    y pídele que reconsidere. Anota qué le faltó ver.\n\n11. Pídele que te redacte la sección de métodos para el modelo de Poisson con\n    spline. Verifica que mencione: los grados de libertad del spline, cómo se\n    eligieron, la prueba contra el modelo lineal y el criterio de bondad de ajuste.\n    Casi siempre se le olvida alguno.\n",
    "supporting": [
      "verificacion-modelos_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}