{
  "hash": "53457de218b95abce2d291d74db5e343",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresiones (parte 1)\"\naliases:\n  - \"/Regresiones1.html\"\n---\n## Paquetes y datos a utilizar\n\nA lo largo de esta sección usaremos los siguientes paquetes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(ggfortify)  #autoplot para diagnósticos\nlibrary(rstanarm)   #para bayesiana\nlibrary(poissonreg) #modelo Poisson\nlibrary(car)        #para el VIF (multicolinealidad)\nlibrary(forecast)   #series de tiempo, la forma clásica\nlibrary(modeltime)  #series de tiempo, la forma tidymodels\nlibrary(timetk)     #utilerías de series de tiempo\n\n#Siempre que uses tidymodels\ntidymodels_prefer()\n```\n:::\n\n\nEn general usaremos la filosofía `tidymodels` para combinar los resultados con el `tidyverse`. Si quieres saber más de `tidymodels` te recomiendo checar [su libro](https://www.tmwr.org) o [su página web](https://www.tidymodels.org/learn/).\n\n::: callout-important\n## En este capítulo todo lo vas a ver de dos formas\n\nEn `R` casi siempre hay **más de una manera** de hacer lo mismo, y las regresiones\nson el caso más claro. Existen dos \"dialectos\":\n\n|                        | La forma clásica            | La forma `tidymodels`         |\n|:-----------------------|:----------------------------|:------------------------------|\n| Regresión lineal       | `lm()`                      | `linear_reg()` + `fit()`      |\n| Regresión logística    | `glm()`                     | `logistic_reg()` + `fit()`    |\n| Series de tiempo       | `forecast` (`auto.arima`)   | `modeltime` (`arima_reg`)     |\n| ¿Cuántos años tiene?   | Desde los inicios de `R`    | Desde \\~2020                  |\n\nVamos a mostrarte **las dos** para cada cosa, con el mismo resultado, porque las\ndos te vas a topar en la vida real: el código viejo (y la mayoría de los libros y\nrespuestas de internet) está en la forma clásica, mientras que el código nuevo\ntiende a usar `tidymodels`.\n\n**Ninguna es mejor que la otra.** La clásica es más corta y directa para un modelo\nsuelto; `tidymodels` es más verbosa pero te da la misma sintaxis para cientos de\nmodelos distintos y te resuelve la validación cruzada y el preprocesamiento, que\nes donde de verdad gana cuando el proyecto crece.\n\n> Tú aprende a leer las dos y escribe en la que te guste. Lo único que no debes\n> hacer es mezclarlas a media línea.\n:::\n\n### Embarazo adolescente y pobreza\n\nPara los datos usaremos la información de [*Utts y Heckard*](https://online.stat.psu.edu/stat462/sites/onlinecourses.science.psu.edu.stat462/files/data/poverty/index.txt) para determinar si hay una relación entre embarazo adolescente y pobreza.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemb_pob <- read_delim(\"https://online.stat.psu.edu/stat462/sites/onlinecourses.science.psu.edu.stat462/files/data/poverty/index.txt\")\n```\n:::\n\n\nLas variables `Brth15to17` y `Brth18to19` son las tasas brutas de natalidad por cada 1000 mujeres (en el año 2002) en adolescentes de 15 a 17 años y de 18 a 19 respectivamente. La variable `PovPct` representa la proporción (%) de la población que vive bajo la línea de pobreza en cada una de las entidades de EEUU (`Location`). Las variables `ViolCrime` y `TeenBrth` no se explican por lo que no las usaremos.\n\n# Regresiones lineales\n\nUsaremos `Brth15to17` y `PovPct` para estudiar si hay una relación entre la tasa de natalidad en adolescentes y el porcentaje de la población en pobreza. Para ello comenzaremos con graficar:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(emb_pob) +\n  geom_point(aes(x = PovPct, y = Brth15to17), color = \"#bc5090\", size = 3) +\n  labs(\n    x = \"Porcentaje en pobreza\",\n    y = \"Tasa bruta de natalidad (por cada 1,000 mujeres adolescentes)\",\n    title = \"Relación entre tasa bruta de natalidad en adolescentes\\nde 15 a 19 años y porcentaje en pobreza\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nParece que a mayor porcentaje de pobreza, mayor tasa bruta de natalidad en adolescentes. \n\n## Planteamiento clásico\n\nSi la relación fuera perfecta todos los casos caerían *exactamente* en una línea recta como sigue:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\ndonde es necesario especificar dos parámetros: el intercepto (el valor que toma cuando la $x$ en este caso `PovPct` vale cero) y la pendiente (el valor que relaciona por cada unidad de aumento en `PovPct` cuánto aumenta `Brth15to17`).\n\nLa ecuación de la línea está dada por:\n\n$$\ny = \\beta_0 + \\beta_1 x\n$$\n\ndonde $\\beta_0$ es el intercepto y $\\beta_1$ la pendiente. Usando la terminología de arriba:\n\n$$\n\\text{Brth15to17} = \\text{Intercepto} + \\text{Pendiente}\\times \\text{PovPct}\n$$ en particular en ese ejemplo:\n\n$$\n\\text{Brth15to17} = 5 + 3\\cdot \\text{PovPct}\n$$\n\nLa idea es que el intercepto ($\\beta_0$ ó $5$) te indica dónde comienza tu línea cuando no tienes $x$'s (es decir cuando $\\text{PovPct} = 0$). El intercepto controla la altura de la línea como puedes ver en la siguiente gráfica donde puse varios interceptos distintos:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\npor otro lado la idea de la pendiente ($\\beta_1$ ó $3$) es retratar cómo cambia la $y$ (en este caso $\\text{Brth15to17}$) por cada unidad que cambia la $x$ (en este caso $\\text{PovPct}$). El valor de $3$ por ejemplo indica que por cada aumento en 1 en $\\text{PovPct}$ la variable $\\text{Brth15to17}$ aumenta en $3$. Este cambio es proporcional; es decir si ahora $\\text{PovPct}$ aumenta 4 (por decir algo) $\\text{Brth15to17}$ aumenta $3\\times 4 = 12$ unidades. La siguiente gráfica muestra varias líneas todas comenzando en el mismo intercepto de $5$:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nComo ya vimos en la primer figura el mundo no es tan perfecto que todo sea una línea recta. Hay un poco de aleatoriedad involucrada (sea por variables no medidas, por errores de medición o porque el mundo no sea determinista). Por lo cual se plantea que en lugar de que la $y$ sea *exactamente* $\\beta_0 + \\beta_1 x$ planteamos que la $y$ proviene de una variable aleatoria normal donde la media de esa normal **es** $\\beta_0 + \\beta_1 x$; es decir:\n\n$$\ny \\sim \\textrm{Normal}( \\beta_0 + \\beta_1 x, \\sigma^2)\n$$\n\no dicho de otra manera:\n\n$$\n\\text{Brth15to17}  \\sim \\textrm{Normal}(\\text{Intercepto} + \\text{Pendiente}\\times \\text{PovPct}, \\sigma^2)\n$$\n\ndonde la $\\sigma^2$ es la varianza de dicha normal. Puesto gráficamente lo que esto quiere decir es que si, por ejemplo, el intercepto es $5$ y la pendiente $3$ entonces cada medición de $y$ viene de una normal ligeramente distinta:\n\n$$\n\\text{Brth15to17}  \\sim \\textrm{Normal}(5 + 3\\times \\text{PovPct}, \\sigma^2)\n$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nDicho de otra forma, suponemos que en un mundo perfecto los valores de $y$ (`Brth15to17`) estarían completamente determinados por los de $x$ (`PovPct`) mediante la ecuación de la recta. **Pero** como el mundo no es perfecto entonces la $y$ proviene de una normal con promedio dado por la recta. Los puntos (como puedes ver an la siguiente gráfica) se centran más en torno a los promedios de las normales sin embargo están colocados aleatoriamente pues corresponden a distintas realizaciones de $y$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nPor ejemplo si el porcentaje de pobreza (`PovPct`) es $10$ entonces la normal de la que provienen estos datos es:\n\n$$\n\\text{Brth15to17}  \\sim \\textrm{Normal}(\\underbrace{5 + 3\\times 10}_{35}, \\sigma^2)\n$$\n\nmientras que si el porcentaje en pobreza es $20$ entonces la normal es:\n\n$$\n\\text{Brth15to17}  \\sim \\textrm{Normal}(\\underbrace{5 + 3\\times 20}_{65}, \\sigma^2)\n$$\n\nPor supuesto que no hay nada de especial con el modelo normal y alguien podría elegir otra distribución (por ejemplo una Gamma) y establecer que:\n\n$$\n\\text{Brth15to17}  \\sim \\textrm{Gamma}(\\text{Intercepto} + \\text{Pendiente}\\times \\text{PovPct}, \\beta)\n$$\n\nEstos modelos son algunos de los lineales generalizados y los discutiremos más adelante. Por ahora nos quedaremos con la idea del modelo dado por:\n\n$$\n\\text{Brth15to17}  \\sim \\textrm{Normal}(\\text{Intercepto} + \\text{Pendiente}\\times \\text{PovPct}, \\sigma^2)\n$$\n\n> **Nota** quizá conoces la regresión lineal bajo la idea clásica de que $$\n> y = \\beta_0 + \\beta_1 x + \\epsilon\n> $$ donde $\\epsilon\\sim\\text{Normal}(0,\\sigma^2)$ son los errores normales. Esta definición es equivalente a la que damos aquí pues por [propiedades aditivas de la normal](https://en.wikipedia.org/wiki/Normal_distribution#Properties) $\\epsilon + \\beta_0 + \\beta_1 x$ se sigue distribuyendo normal pero con la media ahora dada por lo agregado ($\\beta_0 + \\beta_1 x$). Las ventajas de esta notación es que un modelo para regresión Poisson es simplemente: $$\n> y \\sim \\textrm{Poisson}(\\beta_0 + \\beta_1 x)\n> $$ y un modelo para regresión logística es: $$\n> y \\sim \\textrm{Bernoulli}\\big(\\textrm{logit}(\\beta_0 + \\beta_1 x)\\big)\n> $$\n\n## Planteamiento en `R`\n\nLo que nos toca ahora es programar nuestro modelo para ello seguiremos la filosofía de tidymodels que pretende unificar bajo la misma notación todos los modelos. La notación básica es como sigue:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo %>%\n  set_engine(\"tipo de ajuste\") %>%\n  fit(\"formula a ajustar\", data = tus_datos)\n```\n:::\n\n\nA partir del ajuste se pueden predecir cosas con `predict`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo %>%\n  set_engine(\"tipo de ajuste\") %>%\n  fit(\"formula a ajustar\", data = tus_datos) %>%\n  predict()\n```\n:::\n\n\no extraer nuevos datos con `extract_fit_engine` y `tidy`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo %>%\n  set_engine(\"tipo de ajuste\") %>%\n  fit(\"formula a ajustar\", data = tus_datos) %>%\n  extract_fit_engine() %>%\n  tidy()\n```\n:::\n\n\nComencemos con nuestro primer modelo: una regresión lineal clásica dada por:\n\n$$\n\\text{Brth15to17}  \\sim \\textrm{Normal}(\\text{Intercepto} + \\text{Pendiente}\\times \\text{PovPct}, \\sigma^2)\n$$\n\nEn `R` el `engine` que necesitamos es \"lm\" que es el clásico:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Ajusta un modelo lineal \n#Brth15to17 = intercepto + pendiente*PovPct\nmodelo_ajustado <- linear_reg() %>% \n  set_engine(\"lm\") %>%\n  fit(Brth15to17 ~ PovPct, data = emb_pob) #Notación y ~ x\n```\n:::\n\n\nNota que a diferencia de `Stata`, `R` no arroja demasiados resultados. Podemos usar `extract_fit_engine` combinado con `summary` para obtenerlos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Ajusta un modelo lineal \n#Brth15to17 = intercepto + pendiente*PovPct\nmodelo_ajustado %>%\n  extract_fit_engine() %>%\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nstats::lm(formula = Brth15to17 ~ PovPct, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.2275  -3.6554  -0.0407   2.4972  10.5152 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   4.2673     2.5297   1.687    0.098 .  \nPovPct        1.3733     0.1835   7.483 1.19e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.551 on 49 degrees of freedom\nMultiple R-squared:  0.5333,\tAdjusted R-squared:  0.5238 \nF-statistic:    56 on 1 and 49 DF,  p-value: 1.188e-09\n```\n\n\n:::\n:::\n\n\no bien con `tidy` si deseamos nos devuelva una tabla de resultados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Ajusta un modelo lineal\n#Brth15to17 = intercepto + pendiente*PovPct\nmodelo_ajustado %>%\n  extract_fit_engine() %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic       p.value\n  <chr>          <dbl>     <dbl>     <dbl>         <dbl>\n1 (Intercept)     4.27     2.53       1.69 0.0980       \n2 PovPct          1.37     0.184      7.48 0.00000000119\n```\n\n\n:::\n:::\n\n\n### Lo mismo con `lm`: la forma clásica\n\nTodo lo anterior se puede hacer sin `tidymodels`, con la función `lm` que viene\nen `R` desde siempre. La fórmula (`y ~ x`) es **idéntica**; lo que cambia es que\nno hay que declarar el motor ni llamar a `fit`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#La misma regresión, en un solo renglón\nmodelo_clasico <- lm(Brth15to17 ~ PovPct, data = emb_pob)\n```\n:::\n\n\nPara ver los resultados, `summary` directo (sin el `extract_fit_engine`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(modelo_clasico)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Brth15to17 ~ PovPct, data = emb_pob)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.2275  -3.6554  -0.0407   2.4972  10.5152 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   4.2673     2.5297   1.687    0.098 .  \nPovPct        1.3733     0.1835   7.483 1.19e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.551 on 49 degrees of freedom\nMultiple R-squared:  0.5333,\tAdjusted R-squared:  0.5238 \nF-statistic:    56 on 1 and 49 DF,  p-value: 1.188e-09\n```\n\n\n:::\n:::\n\n\nY si quieres la tabla ordenada, `tidy` también funciona sobre un `lm`, porque en\nrealidad `tidy` nunca fue de `tidymodels` sino del paquete `broom`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(modelo_clasico, conf.int = TRUE, conf.level = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic       p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>         <dbl>    <dbl>     <dbl>\n1 (Intercept)     4.27     2.53       1.69 0.0980          0.0260      8.51\n2 PovPct          1.37     0.184      7.48 0.00000000119   1.07        1.68\n```\n\n\n:::\n:::\n\n\nComprobemos que de verdad son el mismo modelo comparando los coeficientes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Los coeficientes de las dos rutas\ncoef(modelo_clasico)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      PovPct \n   4.267293    1.373345 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(extract_fit_engine(modelo_ajustado))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      PovPct \n   4.267293    1.373345 \n```\n\n\n:::\n\n```{.r .cell-code}\n#¿Son iguales?\nall.equal(coef(modelo_clasico), coef(extract_fit_engine(modelo_ajustado)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Tabla de traducción entre los dos dialectos\n\nGuarda esta tabla: te va a servir cada vez que encuentres código en el dialecto\nque no usas.\n\n| Qué quieres                 | Forma clásica                        | Forma `tidymodels`                              |\n|:----------------------------|:-------------------------------------|:------------------------------------------------|\n| Ajustar el modelo           | `lm(y ~ x, data = d)`                | `linear_reg() %>% set_engine(\"lm\") %>% fit(y ~ x, data = d)` |\n| Ver el resumen completo     | `summary(m)`                         | `m %>% extract_fit_engine() %>% summary()`      |\n| Tabla de coeficientes       | `tidy(m)`                            | `tidy(m)`                                       |\n| Coeficientes solos          | `coef(m)`                            | `coef(extract_fit_engine(m))`                   |\n| Predecir                    | `predict(m, newdata = d)`            | `predict(m, new_data = d)`                      |\n| Intervalos de predicción    | `predict(m, newdata = d, interval = \"prediction\")` | `predict(m, new_data = d, type = \"pred_int\")` |\n| Métricas del ajuste         | `glance(m)`                          | `glance(m)`                                     |\n| Diagnósticos                | `autoplot(m, which = 1:5)`           | `autoplot(m, which = 1:5)`                      |\n\n**Ojo con dos detalles que muerden:** en la forma clásica el argumento se llama\n`newdata` (junto) y en `tidymodels` se llama `new_data` (con guion bajo). Y los\nintervalos se piden distinto. Son las dos confusiones más comunes al pasar de un\ndialecto al otro.\n:::\n\n::: {.callout-note collapse=\"true\"}\n### ¿Y entonces para qué sirve `tidymodels` si `lm` es más corto?\n\nBuena pregunta, porque con **un** modelo `lm` gana por mucho. `tidymodels` empieza\na valer la pena cuando:\n\n- Quieres probar **varios modelos distintos** con la misma sintaxis (una lineal,\n  un bosque aleatorio, una red elástica) y comparar. Con la ruta clásica cada uno\n  tiene su función, sus argumentos y su forma de predecir; con `tidymodels` todos\n  se ajustan igual.\n- Necesitas **validación cruzada** o partir en entrenamiento y prueba sin\n  escribirlo a mano.\n- Tienes **preprocesamiento** (estandarizar, crear variables indicadoras, imputar)\n  y quieres que se aplique exactamente igual a los datos nuevos. Ésta es la fuente\n  de errores silenciosos más común en modelos predictivos, y `tidymodels` la\n  resuelve con las `recipes`.\n\nPara un modelo suelto de inferencia —que es la mayoría de lo que se hace en salud\npública— `lm` está perfecto.\n:::\n\nSegún el tipo de regresión que estemos haciendo es el tipo de tabla que regresa `tidy` (ver `?tidy`). En particular, por ejemplo, podemos modificar para que devuelva intervalos de confianza al 90%:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Ajusta un modelo lineal \n#Brth15to17 = intercepto + pendiente*PovPct\nmodelo_ajustado %>%\n  tidy(conf.int = T, conf.level = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic       p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>         <dbl>    <dbl>     <dbl>\n1 (Intercept)     4.27     2.53       1.69 0.0980          0.0260      8.51\n2 PovPct          1.37     0.184      7.48 0.00000000119   1.07        1.68\n```\n\n\n:::\n:::\n\n\nEn este caso, el modelo estima que el intercepto ($\\beta_0$) es $4.27$ y la pendiente ($\\beta_1$) es $1.37$. Como son *estimadores* del verdadero valor se denotan con *gorrito*: $\\hat\\beta_0 = 4.27$ y $\\hat\\beta_1 = 1.37$.\n\nPodemos utilizar la función de `predict` para que el modelo nos muestre cómo cree que son los verdaderos valores en relación a los ajustados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Ajusta un modelo lineal \n#Brth15to17 = intercepto + pendiente*PovPct\npredichos <- modelo_ajustado %>%\n  predict(new_data = emb_pob)\n\nintervalo_predichos <- modelo_ajustado %>%\n  predict(new_data = emb_pob, type = \"pred_int\", level = 0.95)\n\n#Juntamos los predichos con los observados\nobs_y_modelo <- emb_pob %>% \n  cbind(predichos) %>%\n  cbind(intervalo_predichos)\n\n#Graficamos\nggplot(obs_y_modelo) +\n  geom_ribbon(aes(x = PovPct, ymin = .pred_lower, ymax = .pred_upper), \n              fill = \"#003f5c\", linewidth = 1, alpha = 0.5) +\n  geom_point(aes(x = PovPct, y = Brth15to17), color = \"#bc5090\", size = 3) +\n  geom_line(aes(x = PovPct, y = .pred), \n            color = \"#003f5c\", linewidth = 1) +\n  labs(\n    x = \"Porcentaje en pobreza\",\n    y = \"Tasa bruta de natalidad (por cada 1,000 mujeres adolescentes)\",\n    title = \"Relación entre tasa bruta de natalidad en adolescentes\\nde 15 a 19 años y porcentaje en pobreza\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nNada más a ojo no parece que el modelo sea el mejor pues puedes ver que no explica bien la variabilidad (los observados varían mucho respecto al intervalo). La $R^2$, una métrica que explica cuánto de la varianza captura el modelo tampoco es muy buena:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumen_ajuste <- modelo_ajustado %>%\n  extract_fit_engine() %>%\n  summary()\n\n#R^2 clásica\nresumen_ajuste$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.533328\n```\n\n\n:::\n\n```{.r .cell-code}\n#R^2 ajustada\nresumen_ajuste$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.523804\n```\n\n\n:::\n:::\n\n\nPodemos checar las diferentes gráficas de diagnóstico:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggfortify)\nautoplot(modelo_ajustado, which = 1:5)\n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nVeamos qué significa cada una de ellas y juguemos un poco con `R` para irlas modificando.\n\n### Residuales contra ajustados\n\nLos **residuales** son la diferencia entre el modelo ($\\hat{y}$) y lo real $y$. En el caso que estábamos trabajando tenemos que con nuestro modelo podemos predecir los valores de `Brth15to17` a partir del porcentaje en pobreza `PovPct`. A los valores predichos por el modelo de `Brth15to17` les ponemos un gorro encima y los llamamos: $\\widehat{\\text{Brth15to17}}$. Estos están dados por la siguiente función:\n\n$$\n\\widehat{\\text{Brth15to17}} = 4.26 + 1.37 \\cdot \\text{PovPct}\n$$\n\npor ejemplo para el porcentaje en pobreza de $20.1$ obtendríamos:\n\n$$\n\\widehat{\\text{Brth15to17}} = 4.26 + 1.37 \\cdot \\text{PovPct} = 31.797\n$$\n\npor otro lado el verdadero valor de cuando el `PovPct` es $20.1$ (estado de `Alabama`) es $\\text{Brth15to17} = 31.5$. La diferencia entre el verdadero valor ($\\text{Brth15to17} = 31.5$) y el predicho por el modelo ($\\widehat{\\text{Brth15to17}} = 31.797$) se conoce como el residual. La idea es que en un modelo bueno no debe haber patrones en los residuales (todos deben de flotar en torno al cero pero no mostrar un patrón).\n\nVeamoslo en nuestra base:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_y_modelo <- obs_y_modelo %>%\n  mutate(residuales = Brth15to17 - .pred)\n\nggplot(obs_y_modelo) +\n  geom_point(aes(x = .pred, y = residuales), color = \"#ff6361\") +\n  labs(\n    x = \"Valores ajustados (predichos)\",\n    y = \"Residuales\",\n    title = \"Residuales vs ajustados\"\n  ) +\n  theme_bw() +\n  geom_hline(aes(yintercept = 0), linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nEn esta gráfica el modelo predice mejor rumbo al final que en medio y esto parece estar corroborado por la gráfica del modelo (previa). Nada más para darnos una idea veamos una gráfica de *malos* residuales y una de *buenos*\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n### Escala locación\n\nRepresenta la escala locación contra los residuales estandarizados. La idea de la gráfica es ver que la varianza $\\sigma^2$ del modelo no cambie conforme cambia la $x$ (propiedad de *homoscedasticidad*). Para ello graficamos los residuales estandarizados dados por los residuales mismos dividos entre su desviación estándar:\n\n$$\nr_{\\text{Std}} = \\frac{\\hat{y} - y}{\\text{sd}(\\hat{y} - y)} = \\frac{\\text{Residuales}}{\\text{sd}\\big(\\text{Residuales}\\big)}\n$$\n\nestos residuales estandarizados los podemos calcular en `R` como sigue:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_y_modelo <- obs_y_modelo %>%\n  mutate(residuales_std = residuales/sd(residuales))\n```\n:::\n\n\nSi los graficamos contra los valores ajustados no deberíamos de ver ningún patrón:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(obs_y_modelo) +\n  geom_point(aes(x = .pred, y = residuales_std), color = \"#ff6361\") +\n  labs(\n    x = \"Valores ajustados (predichos)\",\n    y = \"Residuales estandarizados\",\n    title = \"Escala Locación\"\n  ) +\n  theme_bw() +\n  geom_hline(aes(yintercept = 0), linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nPodemos ver cómo se ven estos puntos en el modelo ideal vs en un modelo donde la $\\sigma^2$ depende de la $x$:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n### Normal cuantil cuantil\n\nLa segunda gráfica corresponde a una gráfica cuantil cuantil. Esta la utilizamos para verificar la hipótesis de normalidad. En una gráfica cuantil cuantil se grafican los cuantiles de los residuales contra los cuantiles teóricos de la normal. Por ejemplo si la hacemos con sólo 4 puntos se vería algo así:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nPodemos armar una gráfica cuantil cuantil con `ggplot2`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(obs_y_modelo, aes(sample = residuales)) + \n  stat_qq(color = \"#ff6361\") + \n  stat_qq_line(color = \"#58508d\") +\n  theme_bw() +\n  labs(\n    x = \"Cuantiles teóricos de la normal\",\n    y = \"Cuantiles observados de los residuales\",\n    title = \"Gráfica qq\"\n  )\n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nLa idea de la gráfica cuantil cuantil es que los puntos sigan la línea lo más posible. Veamos cómo se ve con los datos bien (y los mal)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n### Residuales contra apalancamiento\n\nEl apalancamiento representa qué tanto cambia el modelo al quitar una sola observación. Para poner un ejemplo considera los siguientes datos donde hay un valor atípico y selecciono dos puntos de interés en dos colores:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nVeamos cómo cambia la regresión si dejo todos los puntos, si quito el normal y si quito el influyente:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nNota que el modelo no cambia prácticamente nada cuando hago la regresión sin el dato que marqué como `normal` pero cambia mucho cuando quito el que marqué como `influyente`. La gráfica de residuales contra apalancamiento muestra también el valor extraño:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nEl apalancamiento mide la influencia de un dato y en `R` se puede calcular con `hatvalues`. Los datos con mayor **apalancamiento** siempre valen la pena checarlos para verificar que todo opera en orden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napalancamiento <- modelo_ajustado %>%\n  extract_fit_engine() %>%\n  hatvalues()\n\nobs_y_modelo <- obs_y_modelo %>%\n  cbind(apalancamiento)\n\n#Graficamos residuales contra apalancamiento\nggplot(obs_y_modelo) +\n  geom_point(aes(x = apalancamiento, y = residuales), color = \"#ff6361\") +\n  labs(\n    x = \"Apalancamiento\",\n    y = \"Residuales\",\n    title = \"Residuales vs ajustados\"\n  ) +\n  theme_bw() +\n  geom_hline(aes(yintercept = 0), linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n### Distancia de Cook\n\nLa distancia de Cook es un concepto similar al apalancamiento que identifica observaciones influyentes. Aquellos valores con distancia de Cook alta vale la pena revisar. En `R` podemos usar `cooks.distance` para calcular la distancia de Cook.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistanciaCook <- modelo_ajustado %>%\n  extract_fit_engine() %>%\n  cooks.distance()\n\nobs_y_modelo <- obs_y_modelo %>%\n  cbind(distanciaCook)\n\n#Graficamos residuales contra apalancamiento\nggplot(obs_y_modelo) +\n  geom_col(aes(x = 1:nrow(obs_y_modelo), y = distanciaCook), fill = \"#ff6361\") +\n  labs(\n    x = \"Observación (número de entrada en la base)\",\n    y = \"Distancia de Cook\",\n    title = \"Distancia de Cook\"\n  ) +\n  theme_bw() \n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\npodemos ver que en el ejemplo anterior (el de la observación influyente) la distancia de Cook es exagerada, tan exagerada que ni se alcanzan a ver los otros:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n## Regresión múltiple: más de una variable\n\nHasta ahora la recta depende de una sola variable. En la vida real casi nunca es\nasí: la tasa de natalidad adolescente no depende sólo de la pobreza. Agregar\nvariables se hace **sumándolas en la fórmula** con un `+`.\n\nLa base también trae `ViolCrime` (una tasa de crimen violento). Agreguémosla:\n\n::: panel-tabset\n### Forma clásica\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_multiple <- lm(Brth15to17 ~ PovPct + ViolCrime, data = emb_pob)\ntidy(modelo_multiple, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term        estimate std.error statistic     p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>       <dbl>    <dbl>     <dbl>\n1 (Intercept)    5.98     2.27        2.64 0.0112         1.43     10.5  \n2 PovPct         1.04     0.183       5.67 0.000000790    0.669     1.40 \n3 ViolCrime      0.344    0.0877      3.93 0.000275       0.168     0.520\n```\n\n\n:::\n:::\n\n\n### Forma `tidymodels`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_multiple_tm <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(Brth15to17 ~ PovPct + ViolCrime, data = emb_pob)\n\ntidy(modelo_multiple_tm, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term        estimate std.error statistic     p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>       <dbl>    <dbl>     <dbl>\n1 (Intercept)    5.98     2.27        2.64 0.0112         1.43     10.5  \n2 PovPct         1.04     0.183       5.67 0.000000790    0.669     1.40 \n3 ViolCrime      0.344    0.0877      3.93 0.000275       0.168     0.520\n```\n\n\n:::\n:::\n\n:::\n\nFíjate en algo importante: **al agregar `ViolCrime`, el coeficiente de `PovPct`\ncambió**. Pasó de $1.37$ a $1.04$. Esto no es un error ni un problema: es la\nnaturaleza de la regresión múltiple.\n\n::: callout-important\n## Cómo se lee un coeficiente en regresión múltiple\n\nEn el modelo de una sola variable, el $1.37$ significaba: *\"por cada punto más de\npobreza, la tasa sube 1.37\"*.\n\nEn el modelo múltiple, el $1.04$ significa: *\"por cada punto más de pobreza, la\ntasa sube 1.04, **manteniendo la tasa de crimen violento constante**\"*.\n\nEse \"manteniendo lo demás constante\" (en latín, *ceteris paribus*) es la frase más\nimportante de toda la regresión múltiple, y es la que más se olvida al escribir\nlos resultados. Los dos coeficientes son correctos: **contestan preguntas\ndistintas.**\n:::\n\n::: callout-warning\nLa documentación de esta base **no explica** qué es exactamente `ViolCrime` ni\n`TeenBrth`. La usamos aquí para mostrar la mecánica del código, pero fíjate en lo\nque eso implica: si no sabes qué mide una variable, no puedes interpretar su\ncoeficiente ni justificar por qué la incluiste. En un análisis de verdad, **eso\nsolo descalifica la variable** para un modelo de inferencia.\n:::\n\n## Comparación de modelos: AIC, BIC y pruebas anidadas\n\nYa tenemos dos modelos. ¿Cuál es mejor? No podemos usar la $R^2$ para decidir,\npor una razón incómoda:\n\n::: callout-important\nLa $R^2$ **siempre** sube (o se queda igual) cuando agregas variables, aunque las\nvariables sean basura pura. Si le agregas a tu modelo una columna de números\naleatorios, la $R^2$ sube. Por eso la $R^2$ **no sirve** para comparar modelos con\ndistinto número de variables.\n:::\n\nPara eso existen los **criterios de información**. Los dos más comunes:\n\n-   El **AIC** (*Akaike Information Criterion*)\n-   El **BIC** (*Bayesian Information Criterion*)\n\nLos dos funcionan igual de raro: **entre más chico, mejor**. Los dos miden qué tan\nbien ajusta el modelo, pero le **cobran una multa por cada parámetro** que uses.\nAsí, una variable sólo \"vale la pena\" si mejora el ajuste más de lo que cuesta la\nmulta. La diferencia entre ellos es que el `BIC` cobra una multa más cara, así que\ntiende a elegir modelos más pequeños.\n\n::: panel-tabset\n### Forma clásica\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Entre más chico, mejor\nAIC(modelo_clasico, modelo_multiple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                df      AIC\nmodelo_clasico   3 323.5094\nmodelo_multiple  4 311.3072\n```\n\n\n:::\n\n```{.r .cell-code}\nBIC(modelo_clasico, modelo_multiple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                df      BIC\nmodelo_clasico   3 329.3049\nmodelo_multiple  4 319.0345\n```\n\n\n:::\n:::\n\n\n### Forma `tidymodels`\n\n`glance` te da el `AIC`, el `BIC` y otras métricas de un jalón, y funciona igual\nen los dos dialectos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  glance(modelo_ajustado)      %>% mutate(modelo = \"PovPct\"),\n  glance(modelo_multiple_tm)   %>% mutate(modelo = \"PovPct + ViolCrime\")\n) %>%\n  select(modelo, r.squared, adj.r.squared, AIC, BIC, df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  modelo             r.squared adj.r.squared   AIC   BIC    df\n  <chr>                  <dbl>         <dbl> <dbl> <dbl> <dbl>\n1 PovPct                 0.533         0.524  324.  329.     1\n2 PovPct + ViolCrime     0.647         0.632  311.  319.     2\n```\n\n\n:::\n:::\n\n:::\n\nEl modelo con las dos variables tiene `AIC` y `BIC` más chicos, así que gana.\n\n### Prueba anidada con `anova`\n\nCuando un modelo está **contenido** en el otro (le llamamos *anidado*: son las\nmismas variables más otras), hay una prueba formal para preguntar si las variables\nextra aportan algo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(modelo_clasico, modelo_multiple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: Brth15to17 ~ PovPct\nModel 2: Brth15to17 ~ PovPct + ViolCrime\n  Res.Df    RSS Df Sum of Sq      F    Pr(>F)    \n1     49 1509.6                                  \n2     48 1142.7  1    366.94 15.413 0.0002753 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nEl valor `p` chiquito nos dice que agregar `ViolCrime` sí mejora el ajuste más de\nlo que se esperaría por azar.\n\n::: callout-warning\n## Tres cosas que hay que tener claras del AIC\n\n1.  **El AIC no dice si tu modelo es bueno**, sólo cuál de los que le diste es\n    *menos malo*. Si todos tus modelos están mal, el AIC te va a elegir uno con\n    toda confianza.\n2.  **Sólo se pueden comparar modelos ajustados a exactamente los mismos datos.**\n    Si un modelo usa una variable con datos faltantes, `R` va a tirar esas filas y\n    los dos modelos ya no serán comparables. Es un error silencioso y frecuente.\n3.  **Los números del AIC no significan nada por sí solos.** Un AIC de `311` no es\n    bueno ni malo; sólo sirve comparado con el `323` del otro modelo. No los\n    reportes sueltos.\n:::\n\n## Multicolinealidad y el VIF\n\nAquí viene el problema que más confunde en regresión múltiple, y lo vamos a ver\ncon un ejemplo donde se nota **muchísimo**.\n\nLa base tiene tres variables de natalidad: `Brth15to17` (tasa en adolescentes de\n15 a 17 años), `Brth18to19` (de 18 a 19) y `TeenBrth`. Por cómo están definidas,\nla tercera **contiene** información de las dos primeras. Metámoslas todas al mismo\nmodelo y veamos qué pasa:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_colineal <- lm(Brth15to17 ~ PovPct + Brth18to19 + TeenBrth, data = emb_pob)\ntidy(modelo_colineal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  -0.583     0.644     -0.906 3.69e- 1\n2 PovPct       -0.0534    0.0464    -1.15  2.56e- 1\n3 Brth18to19   -0.520     0.0502   -10.4   1.04e-13\n4 TeenBrth      1.44      0.0827    17.5   3.56e-22\n```\n\n\n:::\n:::\n\n\nY ahora fíjate en las métricas de ajuste:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(modelo_colineal) %>% select(r.squared, adj.r.squared, AIC, BIC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  r.squared adj.r.squared   AIC   BIC\n      <dbl>         <dbl> <dbl> <dbl>\n1     0.988         0.988  140.  149.\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Un modelo espectacular y completamente inservible\n\nCompara con los modelos anteriores: la $R^2$ pasó de $0.53$ a **$0.99$** y el\n`AIC` se derrumbó de $323$ a **$140$**. Por cualquier criterio de los que acabamos\nde ver, **éste es por mucho el mejor modelo.**\n\nY sin embargo mira los coeficientes:\n\n-   El de `PovPct` **cambió de signo**: pasó de $+1.37$ a $-0.05$, y dejó de ser\n    distinguible de cero. ¿La pobreza ahora *reduce* la natalidad adolescente?\n-   El de `Brth18to19` es **negativo** ($-0.52$): ¿más nacimientos en las de 18 a\n    19 significan *menos* nacimientos en las de 15 a 17?\n\nNinguna de las dos cosas tiene el menor sentido. Éste es el mejor ejemplo posible\nde lo que vimos en el [capítulo de modelos](modelos.qmd): **un modelo puede ser\nexcelente para predecir y una fuente de conclusiones falsas si lo lees como si\nfuera de inferencia.**\n:::\n\n¿Por qué pasó esto? Porque las variables **se explican unas a otras**. Cuando dos\nvariables cargan casi la misma información, el modelo no puede decidir a cuál\ndarle el crédito, así que reparte los coeficientes de forma inestable: uno gigante\npositivo, otro gigante negativo, y las predicciones salen bien de milagro.\n\n### Cómo se detecta: el `VIF`\n\nEl **VIF** (*Variance Inflation Factor*, factor de inflación de la varianza) mide\nexactamente esto: para cada variable, cuánto se infla su varianza por culpa de\nestar correlacionada con las demás. Se calcula con `vif` del paquete `car`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Nuestro modelo bueno\nvif(modelo_multiple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   PovPct ViolCrime \n 1.282857  1.282857 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#El modelo con el problema\nvif(modelo_colineal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    PovPct Brth18to19   TeenBrth \n  2.442371  56.289092  64.369636 \n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Cómo leer el VIF\n\nEl VIF vale como mínimo `1` (esa variable no comparte nada con las otras) y no\ntiene máximo.\n\n| VIF          | Interpretación                                              |\n|:-------------|:------------------------------------------------------------|\n| $\\approx 1$  | Sin problema.                                               |\n| $< 5$        | Tolerable, es lo normal en datos reales.                    |\n| $5$ a $10$   | Sospechoso, vale la pena revisar.                           |\n| $> 10$       | Problema serio de multicolinealidad.                        |\n\nEn nuestro modelo bueno los dos VIF son $1.28$: perfecto. En el modelo colineal\nson **$56$ y $64$**, o sea cinco a seis veces arriba del umbral de alarma.\n\nHay una regla mnemotécnica útil: $\\sqrt{\\text{VIF}}$ te dice por cuánto se\nmultiplicó el error estándar de ese coeficiente. Un VIF de $64$ significa que el\nerror estándar es **8 veces más grande** de lo que sería sin colinealidad.\n:::\n\n### ¿Y qué se hace al respecto?\n\nLa multicolinealidad no se \"arregla\" con un comando; se resuelve pensando:\n\n1.  **Quita variables redundantes.** Si `TeenBrth` ya contiene a las otras dos,\n    escoge una y ya. Es la solución correcta el 90% de las veces.\n2.  **Combínalas** en un solo indicador si tiene sentido conceptual.\n3.  **No hagas nada** — si tu modelo es puramente de predicción y no vas a\n    interpretar ningún coeficiente, la colinealidad no te estorba. Las\n    predicciones del modelo colineal son de hecho buenísimas.\n\n::: callout-warning\nLa decisión de qué variable quitar es **conceptual, no estadística**. No dejes que\nel VIF elija por ti: elige tú con base en qué significa cada variable y qué\npregunta estás contestando.\n:::\n\n### Ejercicio (VIF y AIC)\n\n1.  Ajusta el modelo `Brth15to17 ~ PovPct + TeenBrth` (sólo dos predictores) y\n    calcula su `VIF` y su `AIC`. ¿Sigue habiendo problema de colinealidad? ¿Cómo se\n    compara el `AIC` con el del modelo de tres variables?\n\n2.  Calcula la matriz de correlaciones de todas las variables numéricas con\n    `cor(emb_pob[,-1])`. Antes de verla, **predice** cuáles dos variables van a\n    tener la correlación más alta. ¿Le atinaste?\n\n3.  Si tuvieras que reportar en un informe **un solo** modelo para contestar\n    *\"¿la pobreza está asociada a la natalidad adolescente?\"*, ¿cuál de los tres\n    elegirías y por qué? Nota que **no** es el del mejor AIC. Escribe tu\n    justificación en tres renglones.\n\n::: {.callout-note collapse=\"true\"}\n### Respuesta del punto 3\n\nEl de `Brth15to17 ~ PovPct`, o cuando mucho el que agrega `ViolCrime` si pudieras\njustificar conceptualmente por qué ajustas por crimen violento.\n\nEl modelo de tres variables tiene el mejor AIC y es **inutilizable** para esta\npregunta: ajustar por `Brth18to19` y `TeenBrth` es ajustar por variables que son\nprácticamente el mismo desenlace que estás midiendo. El coeficiente de pobreza que\nsale de ahí no contesta la pregunta que te hicieron.\n\nEs el punto central del capítulo de modelos: **primero decides qué pregunta\ntienes, y sólo entonces eliges el criterio.** El AIC es una herramienta para\nelegir entre modelos que ya tienen sentido, no un sustituto de pensar.\n:::\n\n## Series de tiempo: `forecast` clásico y `modeltime`\n\nLas regresiones que hemos visto no tienen tiempo: cada fila es un estado y el\norden no importa. Cuando los datos son una **serie de tiempo** (una medición por\ndía, por semana, por año) el orden sí importa y hacen falta otras herramientas.\n\nAquí también hay dos dialectos: `forecast` (el clásico, de Rob Hyndman) y\n`modeltime` (que es la versión `tidymodels`). Usaremos los casos diarios de\nenfermedades respiratorias del SINAVE:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nserie_covid <- read_csv(\"datasets/casos_covid_agosto_2022.csv\") %>%\n  rename(fecha = FECHA_SINTOMAS, casos = n) %>%\n  arrange(fecha)\n\n#Así se ven los datos\nhead(serie_covid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  fecha      casos\n  <date>     <dbl>\n1 2020-01-01   287\n2 2020-01-02   233\n3 2020-01-03   247\n4 2020-01-04   245\n5 2020-01-05   349\n6 2020-01-06   345\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(serie_covid) +\n  geom_line(aes(x = fecha, y = casos), color = \"#003f5c\") +\n  labs(x = \"\", y = \"Casos\") +\n  scale_y_continuous(labels = scales::label_comma()) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Casos diarios registrados en el SINAVE.](regresiones-1_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n### La forma clásica: `forecast`\n\nEn el mundo clásico, una serie de tiempo se guarda en un objeto especial (`ts`)\ndonde le dices cada cuántas observaciones se repite el patrón. Como son datos\ndiarios con patrón semanal, la frecuencia es `7`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#frequency = 7 porque el patrón se repite cada semana\nserie_ts <- ts(serie_covid$casos, frequency = 7)\n\n#auto.arima elige solo el tipo de modelo ARIMA\nmodelo_arima <- auto.arima(serie_ts)\nmodelo_arima\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: serie_ts \nARIMA(2,0,2)(2,1,0)[7] \n\nCoefficients:\n         ar1      ar2      ma1     ma2     sar1     sar2\n      1.9146  -0.9276  -1.4958  0.6152  -0.5220  -0.2266\ns.e.  0.0178   0.0174   0.0318  0.0320   0.0329   0.0325\n\nsigma^2 = 11627635:  log likelihood = -9074.54\nAIC=18163.09   AICc=18163.21   BIC=18197.08\n```\n\n\n:::\n:::\n\n\nPara pronosticar las siguientes dos semanas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npronostico <- forecast(modelo_arima, h = 14)\nautoplot(pronostico) +\n  labs(x = \"Semanas\", y = \"Casos\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Pronóstico a 14 días con el método clásico.](regresiones-1_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\n::: callout-warning\n## Revisa el paso 3 del flujo de trabajo\n\nMira los valores que pronosticó el modelo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(head(as.numeric(pronostico$mean), 5), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  7785.5  2058.5   -10.9 -2781.3 -3821.2\n```\n\n\n:::\n:::\n\n\nHay un pronóstico **negativo**. El modelo está prediciendo un número negativo de\ncasos de una enfermedad, que es imposible.\n\nEsto no es un error de programación: es que un `ARIMA` supone que los datos son\ncontinuos y pueden tomar cualquier valor, y nosotros le dimos **conteos** que\nnunca pueden bajar de cero. Es exactamente el problema del\n[paso 3 del flujo de trabajo](modelos.qmd#un-flujo-de-trabajo-más-detallado):\nsi hubieras simulado del modelo antes de ajustarlo, lo habrías visto.\n\nLa solución honesta es modelar los conteos con algo apropiado (por ejemplo un\nmodelo Poisson o binomial negativo, o modelar el logaritmo de los casos), no\ntruncar los negativos a cero y seguir como si nada.\n:::\n\n### La forma `tidymodels`: `modeltime`\n\n`modeltime` hace lo mismo con la sintaxis de `tidymodels`. La diferencia grande es\nque te obliga (para bien) a **partir los datos** en entrenamiento y prueba, para\nque evalúes el pronóstico contra datos que el modelo no vio:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Apartamos los últimos 14 días para evaluar\nparticion <- time_series_split(\n  serie_covid,\n  date_var   = fecha,\n  assess     = \"14 days\",\n  cumulative = TRUE\n)\n\n#Mismo auto.arima, sintaxis tidymodels\nmodelo_arima_tm <- arima_reg() %>%\n  set_engine(\"auto_arima\") %>%\n  fit(casos ~ fecha, data = training(particion))\n```\n:::\n\n\nAhora lo calibramos contra los datos que apartamos y medimos qué tan bien le fue:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_modelos <- modeltime_table(modelo_arima_tm) %>%\n  modeltime_calibrate(new_data = testing(particion))\n\ntabla_modelos %>%\n  modeltime_accuracy() %>%\n  select(.model_desc, mae, rmse, rsq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  .model_desc              mae  rmse   rsq\n  <chr>                  <dbl> <dbl> <dbl>\n1 ARIMA(2,0,2)(2,1,0)[7] 6570. 8599. 0.295\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Aquí sí gana `tidymodels`\n\nNota lo que acaba de pasar: la ruta clásica te dio un pronóstico bonito y **nunca\nte dijo si era bueno**. La ruta `modeltime` te obligó a apartar datos y te dio un\nerror medio absoluto (`mae`) medido contra datos reales que el modelo no vio.\n\nÉsa es la diferencia entre el paso 4 y el paso 7 del flujo de trabajo. Y en\npredicción, saltarse el paso 7 es la falla más grave que puedes cometer: un\npronóstico sin evaluar no es un pronóstico, es un dibujo.\n\nSe puede hacer perfectamente con `forecast` a mano (partiendo la serie tú), pero\n`modeltime` no te deja olvidarlo.\n:::\n\n### Ejercicio (series de tiempo)\n\n1.  Cambia el `assess = \"14 days\"` por `assess = \"60 days\"` y vuelve a calcular la\n    exactitud. ¿Mejoró o empeoró el `mae`? ¿Por qué tiene sentido?\n\n2.  Ajusta la serie con `frequency = 365` en lugar de `7` en la ruta clásica.\n    ¿Cambió el modelo que eligió `auto.arima`? ¿Qué patrón estás suponiendo con\n    cada frecuencia?\n\n3.  **A mano.** Mira la gráfica de la serie completa y dibuja en tu cuaderno cómo\n    crees que debería verse un pronóstico razonable a 14 días. Después compáralo\n    con lo que produjo el modelo. ¿El modelo captó la tendencia que tú viste?\n\n4.  Ajusta un segundo modelo con `exp_smoothing()` (suavizamiento exponencial),\n    agrégalo a la `modeltime_table` junto al `ARIMA` y compara los dos con\n    `modeltime_accuracy()`. ¿Cuál pronostica mejor?\n\n## Ejercicio\n\n1.  Corre el siguiente código para generar una base de datos de nombre `datLong` que contiene $4$ grupos. Para cada grupo genere una regresión lineal de la forma:\n\n$$\ny = \\beta_0 + \\beta_1 x\n$$\n\nIdentifica cuáles regresiones sí ajustan bien y cuáles no mediante los gráficos de diagnóstico. Finalmente grafica tus datos $x$ contra $y$ y la regresión para ver que lo hayas hecho bien. ¿Hay alguna forma de corregir alguna de las que no ajusta bien?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- datasets::anscombe\ndatLong <- data.frame(\n    grupo  = rep(1:4, each = 11),\n    x = unlist(dat[,c(1:4)]),\n    y = unlist(dat[,c(5:8)])\n    )\nrownames(datLong) <- NULL\n```\n:::\n\n\n2.  Lee la base de datos de $n = 345$ niños entre $6$ y $10$ años de Kahn, Michael (2005). Las variables de interés son $y = \\text{FEV}$ el volumen de expiración forzada y $x = \\text{edad}$ en años. Realiza una regresión lineal. Justifica que no se cumple la homocedasticidad mediante una gráfica de escala locación.\n\n3.  Plantee una regresión lineal usando [los datos de esta liga](https://data.princeton.edu/wws509/datasets/#salary) para determinar si el sexo influye en el salario. **Ojo** en la regresión es necesario incluir otras covariables.\n\n## ¿Y si lo hacemos bayesiano?\n\nPara hacer la misma regresión lineal pero con estadística bayesiana podemos nada más cambiar el `engine`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Ajusta un modelo lineal \n#Brth15to17 = intercepto + pendiente*PovPct\nmodelo_bayesiano <- linear_reg() %>% \n  set_engine(\"stan\") %>%\n  fit(Brth15to17 ~ PovPct, data = emb_pob) #Notación y ~ x\n```\n:::\n\n\nY podemos ver el ajuste:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_bayesiano %>%\n  extract_fit_engine() %>%\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       gaussian [identity]\n formula:      Brth15to17 ~ PovPct\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 51\n predictors:   2\n\nEstimates:\n              mean   sd   10%   50%   90%\n(Intercept) 4.3    2.6  1.1   4.3   7.6  \nPovPct      1.4    0.2  1.1   1.4   1.6  \nsigma       5.6    0.6  5.0   5.6   6.4  \n\nFit Diagnostics:\n           mean   sd   10%   50%   90%\nmean_PPD 22.3    1.1 20.9  22.3  23.7 \n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse Rhat n_eff\n(Intercept)   0.0  1.0  3556 \nPovPct        0.0  1.0  3463 \nsigma         0.0  1.0  3411 \nmean_PPD      0.0  1.0  3897 \nlog-posterior 0.0  1.0  1702 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n\no realizar predicciones:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredichos <- modelo_bayesiano %>%\n  extract_fit_engine() %>%\n  predict(new_data = emb_pob)\n\nic <- modelo_bayesiano %>%\n  extract_fit_engine() %>%\n  predictive_interval(newdata = emb_pob, prob = 0.95) #Para bayesiana\n\n#Juntamos los predichos con los observados\nobs_y_modelo <- emb_pob %>% \n  cbind(predichos) %>%\n  cbind(ic)\n\n#Graficamos\nggplot(obs_y_modelo) +\n  geom_ribbon(aes(x = PovPct, ymin = `2.5%`, ymax = `97.5%`), \n              fill = \"#003f5c\", linewidth = 1, alpha = 0.5) +\n  geom_point(aes(x = PovPct, y = Brth15to17), color = \"#ffa600\", size = 3) +\n  geom_line(aes(x = PovPct, y = predichos), \n            color = \"#003f5c\", linewidth = 1) +\n  labs(\n    x = \"Porcentaje en pobreza\",\n    y = \"Tasa bruta de natalidad (por cada 1,000 mujeres adolescentes)\",\n    title = \"Relación entre tasa bruta de natalidad en adolescentes\\nde 15 a 19 años y porcentaje en pobreza\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\nPara validación del modelo puedes checar [esta página](https://mc-stan.org/rstanarm/articles/rstanarm.html#step-3-criticize-the-model-1) que explica `loo` ([ver paper](https://arxiv.org/abs/1507.04544):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_bayesiano %>%\n  extract_fit_engine() %>% \n  loo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nComputed from 4000 by 51 log-likelihood matrix.\n\n         Estimate  SE\nelpd_loo   -161.5 4.2\np_loo         2.4 0.5\nlooic       323.1 8.4\n------\nMCSE of elpd_loo is 0.0.\nMCSE and ESS estimates assume independent draws (r_eff=1).\n\nAll Pareto k estimates are good (k < 0.7).\nSee help('pareto-k-diagnostic') for details.\n```\n\n\n:::\n:::\n\n\nasi como su visualización (si el modelo no fuera bueno)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_bayesiano %>%\n  extract_fit_engine() %>% \n  loo() %>%\n  plot(label_points = TRUE)\n```\n\n::: {.cell-output-display}\n![](regresiones-1_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\n## Ejercicio\n\n1.  Utilice las opciones de `engine` para cambiar el `prior_intercept` del intercepto a una `t` de Student y el `prior` de los coeficientes a una `Laplace`. ¿Cambia mucho el resultado?\n\n# Continuación\n\n[Ve a regresiones parte 2](regresiones-2.qmd)\n\n# Sistema\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessioninfo::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.5.3 (2026-03-11)\n os       macOS Sequoia 15.7.3\n system   x86_64, darwin20\n ui       X11\n language (EN)\n collate  es_ES.UTF-8\n ctype    es_ES.UTF-8\n tz       America/Mexico_City\n date     2026-07-29\n pandoc   3.10.1 @ /usr/local/bin/ (via rmarkdown)\n quarto   1.10.18 @ /usr/local/bin/quarto\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package        * version     date (UTC) lib source\n abind            1.4-8       2024-09-12 [1] CRAN (R 4.5.0)\n backports        1.5.1       2026-04-03 [1] CRAN (R 4.5.2)\n base64enc        0.1-6       2026-02-02 [1] CRAN (R 4.5.1)\n bayesplot        1.15.0.9000 2026-04-17 [1] https://stan-dev.r-universe.dev (R 4.5.3)\n bit              4.6.0       2025-03-06 [1] CRAN (R 4.5.0)\n bit64            4.8.2       2026-05-19 [1] CRAN (R 4.5.2)\n boot             1.3-32      2025-08-29 [1] CRAN (R 4.5.3)\n broom          * 1.0.12      2026-01-27 [1] CRAN (R 4.5.1)\n cachem           1.1.0       2024-05-16 [1] CRAN (R 4.5.0)\n car            * 3.1-5       2026-02-03 [1] CRAN (R 4.5.1)\n carData        * 3.0-6       2026-01-30 [1] CRAN (R 4.5.1)\n checkmate        2.3.4       2026-02-03 [1] CRAN (R 4.5.1)\n class            7.3-23      2025-01-01 [1] CRAN (R 4.5.3)\n cli              3.6.6       2026-04-09 [1] CRAN (R 4.5.2)\n codetools        0.2-20      2024-03-31 [1] CRAN (R 4.5.3)\n colorspace       2.1-2       2025-09-22 [1] CRAN (R 4.5.1)\n colourpicker     1.3.0       2023-08-21 [1] CRAN (R 4.5.0)\n conflicted       1.2.0       2023-02-01 [1] CRAN (R 4.5.0)\n cowplot        * 1.2.0       2025-07-07 [1] CRAN (R 4.5.1)\n crayon           1.5.3       2024-06-20 [1] CRAN (R 4.5.0)\n crosstalk        1.2.2       2025-08-26 [1] CRAN (R 4.5.1)\n curl             7.1.0       2026-04-22 [1] CRAN (R 4.5.2)\n data.table       1.18.4      2026-05-06 [1] CRAN (R 4.5.2)\n dials          * 1.4.2       2025-09-04 [1] CRAN (R 4.5.1)\n DiceDesign       1.10        2023-12-07 [1] CRAN (R 4.5.0)\n digest           0.6.39      2025-11-19 [1] CRAN (R 4.5.1)\n distributional   0.8.1       2026-06-27 [1] CRAN (R 4.5.2)\n dplyr          * 1.2.1       2026-04-03 [1] CRAN (R 4.5.2)\n DT               0.34.0      2025-09-02 [1] CRAN (R 4.5.1)\n dygraphs         1.1.1.6     2018-07-11 [1] CRAN (R 4.5.0)\n evaluate         1.0.5       2025-08-27 [1] CRAN (R 4.5.1)\n farver           2.1.2       2024-05-13 [1] CRAN (R 4.5.0)\n fastmap          1.2.0       2024-05-15 [1] CRAN (R 4.5.0)\n forcats        * 1.0.1       2025-09-25 [1] CRAN (R 4.5.1)\n forecast       * 9.0.2       2026-03-18 [1] CRAN (R 4.5.2)\n Formula          1.2-5       2023-02-24 [1] CRAN (R 4.5.0)\n fracdiff         1.5-3       2024-02-01 [1] CRAN (R 4.5.0)\n furrr            0.3.1       2022-08-15 [1] CRAN (R 4.5.0)\n future           1.70.0      2026-03-14 [1] CRAN (R 4.5.2)\n future.apply     1.20.2      2026-02-20 [1] CRAN (R 4.5.2)\n generics         0.1.4       2025-05-09 [1] CRAN (R 4.5.0)\n ggfortify      * 0.4.19      2025-07-27 [1] CRAN (R 4.5.1)\n ggplot2        * 4.0.3       2026-04-22 [1] CRAN (R 4.5.2)\n ggridges       * 0.5.7       2025-08-27 [1] CRAN (R 4.5.1)\n globals          0.19.1      2026-03-13 [1] CRAN (R 4.5.2)\n glue             1.8.1       2026-04-17 [1] CRAN (R 4.5.2)\n gower            1.0.2       2024-12-17 [1] CRAN (R 4.5.0)\n GPfit            1.0-9       2025-04-12 [1] CRAN (R 4.5.0)\n gridExtra        2.3         2017-09-09 [1] CRAN (R 4.5.0)\n gtable           0.3.6       2024-10-25 [1] CRAN (R 4.5.0)\n gtools           3.9.5       2023-11-20 [1] CRAN (R 4.5.0)\n hardhat          1.4.2       2025-08-20 [1] CRAN (R 4.5.1)\n hms              1.1.4       2025-10-17 [1] CRAN (R 4.5.1)\n htmltools        0.5.9       2025-12-04 [1] CRAN (R 4.5.1)\n htmlwidgets      1.6.4       2023-12-06 [1] CRAN (R 4.5.0)\n httpuv           1.6.17      2026-03-18 [1] CRAN (R 4.5.2)\n igraph           2.2.2       2026-02-12 [1] CRAN (R 4.5.2)\n infer          * 1.1.0       2025-12-18 [1] CRAN (R 4.5.1)\n inline           0.3.21      2025-01-09 [1] CRAN (R 4.5.0)\n ipred            0.9-15      2024-07-18 [1] CRAN (R 4.5.0)\n janitor          2.2.1       2024-12-22 [1] CRAN (R 4.5.0)\n jsonlite         2.0.0       2025-03-27 [1] CRAN (R 4.5.0)\n knitr            1.51        2025-12-20 [1] CRAN (R 4.5.1)\n labeling         0.4.3       2023-08-29 [1] CRAN (R 4.5.0)\n later            1.4.8       2026-03-05 [1] CRAN (R 4.5.2)\n lattice          0.22-9      2026-02-09 [1] CRAN (R 4.5.3)\n lava             1.8.2       2025-10-30 [1] CRAN (R 4.5.1)\n lhs              1.2.1       2026-03-01 [1] CRAN (R 4.5.2)\n lifecycle        1.0.5       2026-01-08 [1] CRAN (R 4.5.1)\n listenv          0.10.1      2026-03-10 [1] CRAN (R 4.5.2)\n lme4             2.0-6       2026-07-16 [1] CRAN (R 4.5.2)\n loo              2.10.0.9000 2026-07-10 [1] https://stan-dev.r-universe.dev (R 4.5.3)\n lubridate      * 1.9.5       2026-02-04 [1] CRAN (R 4.5.1)\n magrittr         2.0.5       2026-04-04 [1] CRAN (R 4.5.2)\n markdown         2.0         2025-03-23 [1] CRAN (R 4.5.0)\n MASS             7.3-65      2025-02-28 [1] CRAN (R 4.5.3)\n Matrix           1.7-5       2026-03-21 [1] CRAN (R 4.5.2)\n matrixStats      1.5.0       2025-01-07 [1] CRAN (R 4.5.0)\n memoise          2.0.1       2021-11-26 [1] CRAN (R 4.5.0)\n mgcv             1.9-4       2025-11-07 [1] CRAN (R 4.5.3)\n mime             0.13        2025-03-17 [1] CRAN (R 4.5.0)\n miniUI           0.1.2       2025-04-17 [1] CRAN (R 4.5.0)\n minqa            1.2.8       2024-08-17 [1] CRAN (R 4.5.0)\n modeldata      * 1.5.1       2025-08-22 [1] CRAN (R 4.5.1)\n modeltime      * 1.3.5       2026-01-31 [1] CRAN (R 4.5.1)\n nlme             3.1-168     2025-03-31 [1] CRAN (R 4.5.3)\n nloptr           2.2.1       2025-03-17 [1] CRAN (R 4.5.0)\n nnet             7.3-20      2025-01-01 [1] CRAN (R 4.5.3)\n otel             0.2.0       2025-08-29 [1] CRAN (R 4.5.1)\n parallelly       1.47.0      2026-04-17 [1] CRAN (R 4.5.2)\n parsnip        * 1.4.1       2026-01-11 [1] CRAN (R 4.5.1)\n pillar           1.11.1      2025-09-17 [1] CRAN (R 4.5.1)\n pkgbuild         1.4.8       2025-05-26 [1] CRAN (R 4.5.0)\n pkgconfig        2.0.3       2019-09-22 [1] CRAN (R 4.5.0)\n plyr             1.8.9       2023-10-02 [1] CRAN (R 4.5.0)\n poissonreg     * 1.0.2       2026-04-20 [1] CRAN (R 4.5.2)\n posterior        1.7.1       2026-07-15 [1] https://stan-dev.r-universe.dev (R 4.5.3)\n prodlim          2026.03.11  2026-03-11 [1] CRAN (R 4.5.2)\n promises         1.5.0       2025-11-01 [1] CRAN (R 4.5.1)\n purrr          * 1.2.2       2026-04-10 [1] CRAN (R 4.5.2)\n QuickJSR         1.10.0      2026-05-17 [1] CRAN (R 4.5.2)\n R6               2.6.1       2025-02-15 [1] CRAN (R 4.5.0)\n rbibutils        2.4.1       2026-01-21 [1] CRAN (R 4.5.1)\n RColorBrewer     1.1-3       2022-04-03 [1] CRAN (R 4.5.0)\n Rcpp           * 1.1.2       2026-07-05 [1] CRAN (R 4.5.2)\n RcppParallel     5.1.11-2    2026-03-05 [1] CRAN (R 4.5.2)\n Rdpack           2.6.6       2026-02-08 [1] CRAN (R 4.5.1)\n readr          * 2.2.0       2026-02-19 [1] CRAN (R 4.5.2)\n recipes        * 1.3.1       2025-05-21 [1] CRAN (R 4.5.0)\n reformulas       0.4.4       2026-02-02 [1] CRAN (R 4.5.1)\n reshape2         1.4.5       2025-11-12 [1] CRAN (R 4.5.1)\n rlang            1.3.0       2026-07-05 [1] CRAN (R 4.5.2)\n rmarkdown        2.31        2026-03-26 [1] CRAN (R 4.5.2)\n rpart            4.1.24      2025-01-07 [1] CRAN (R 4.5.3)\n rsample        * 1.3.2       2026-01-30 [1] CRAN (R 4.5.1)\n rstan            2.36.0.9000 2026-05-22 [1] https://stan-dev.r-universe.dev (R 4.5.3)\n rstanarm       * 2.32.2      2025-09-30 [1] CRAN (R 4.5.1)\n rstantools       2.6.0.9000  2026-01-10 [1] https://stan-dev.r-universe.dev (R 4.5.3)\n rstudioapi       0.19.0      2026-06-11 [1] CRAN (R 4.5.2)\n S7               0.2.2       2026-04-22 [1] CRAN (R 4.5.2)\n scales         * 1.4.0       2025-04-24 [1] CRAN (R 4.5.0)\n sessioninfo      1.2.3       2025-02-05 [1] CRAN (R 4.5.0)\n shiny            1.13.0      2026-02-20 [1] CRAN (R 4.5.2)\n shinyjs          2.1.1       2026-01-15 [1] CRAN (R 4.5.1)\n shinystan        2.7.0       2025-12-12 [1] CRAN (R 4.5.1)\n shinythemes      1.2.0       2021-01-25 [1] CRAN (R 4.5.0)\n snakecase        0.11.1      2023-08-27 [1] CRAN (R 4.5.0)\n sparsevctrs      0.3.6       2026-01-27 [1] CRAN (R 4.5.1)\n StanHeaders      2.36.0.9000 2026-05-22 [1] https://stan-dev.r-universe.dev (R 4.5.3)\n stringi          1.8.7       2025-03-27 [1] CRAN (R 4.5.0)\n stringr        * 1.6.0       2025-11-04 [1] CRAN (R 4.5.1)\n survival         3.8-6       2026-01-16 [1] CRAN (R 4.5.3)\n tailor         * 0.1.0       2025-08-25 [1] CRAN (R 4.5.1)\n tensorA          0.36.2.1    2023-12-13 [1] CRAN (R 4.5.0)\n threejs          0.3.4       2025-04-21 [1] CRAN (R 4.5.0)\n tibble         * 3.3.1       2026-01-11 [1] CRAN (R 4.5.1)\n tidymodels     * 1.4.1       2025-09-08 [1] CRAN (R 4.5.1)\n tidyr          * 1.3.2       2025-12-19 [1] CRAN (R 4.5.1)\n tidyselect       1.2.1       2024-03-11 [1] CRAN (R 4.5.0)\n tidyverse      * 2.0.0       2023-02-22 [1] CRAN (R 4.5.0)\n timechange       0.4.0       2026-01-29 [1] CRAN (R 4.5.1)\n timeDate         4052.112    2026-01-28 [1] CRAN (R 4.5.1)\n timetk         * 2.9.1       2025-08-29 [1] CRAN (R 4.5.1)\n tune           * 2.0.1       2025-10-17 [1] CRAN (R 4.5.1)\n tzdb             0.5.0       2025-03-15 [1] CRAN (R 4.5.0)\n urca             1.3-4       2024-05-27 [1] CRAN (R 4.5.0)\n utf8             1.2.6       2025-06-08 [1] CRAN (R 4.5.0)\n V8               8.2.0       2026-04-21 [1] CRAN (R 4.5.2)\n vctrs            0.7.3       2026-04-11 [1] CRAN (R 4.5.2)\n vroom            1.7.1       2026-03-31 [1] CRAN (R 4.5.2)\n withr            3.0.3       2026-06-19 [1] CRAN (R 4.5.2)\n workflows      * 1.3.0       2025-08-27 [1] CRAN (R 4.5.1)\n workflowsets   * 1.1.1       2025-05-27 [1] CRAN (R 4.5.0)\n xfun             0.60        2026-07-09 [1] CRAN (R 4.5.2)\n xtable           1.8-8       2026-02-22 [1] CRAN (R 4.5.2)\n xts              0.14.2      2026-02-28 [1] CRAN (R 4.5.2)\n yaml             2.3.12      2025-12-10 [1] CRAN (R 4.5.1)\n yardstick      * 1.3.2       2025-01-22 [1] CRAN (R 4.5.0)\n zoo              1.8-15      2025-12-15 [1] CRAN (R 4.5.1)\n\n [1] /Library/Frameworks/R.framework/Versions/4.5-x86_64/Resources/library\n * ── Packages attached to the search path.\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "regresiones-1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}